package service

const (
	ERROR_CODE_MSG_HISTORY_PROTOCOL_UNMARSHAL_ERR int32 = 81001
	ERROR_CODE_MSG_HISTORY_GRPC_SERVICE_FAILURE   int32 = 81002
	ERROR_CODE_MSG_HISTORY_MSG_PUSH_FAILED        int32 = 81003
	ERROR_CODE_MSG_HISTORY_MSG_ENQUEUE_FAILED     int32 = 81004
	ERROR_CODE_MSG_HISTORY_GET_SEQ_ID_FAILED      int32 = 81005
	ERROR_CODE_MSG_HISTORY_INSERT_MESSAGE_FAILED  int32 = 81006
	ERROR_CODE_MSG_HISTORY_CHCHE_MESSAGE_FAILED   int32 = 81007
	ERROR_CODE_MSG_HISTORY_UPDATE_VALUE_FAILED    int32 = 81008
)

const (
	ERROR_MSG_HISTORY_PROTOCOL_UNMARSHAL_ERR = "协议反序列化错误"
	ERROR_MSG_HISTORY_GRPC_SERVICE_FAILURE   = "服务故障"
	ERROR_MSG_HISTORY_MSG_PUSH_FAILED        = "消息推送失败"
	ERROR_MSG_HISTORY_MSG_ENQUEUE_FAILED     = "消息ENQUEUE失败"
	ERROR_MSG_HISTORY_GET_SEQ_ID_FAILED      = "生成 SEQUENCE ID 失败"
	ERROR_MSG_HISTORY_INSERT_MESSAGE_FAILED  = "消息入库失败"
	ERROR_MSG_HISTORY_CHCHE_MESSAGE_FAILED   = "消息缓存失败"
	ERROR_MSG_HISTORY_UPDATE_VALUE_FAILED    = "更新Value失败"
)
