// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: pb_req/req.proto

package pb_req

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	pb_enum "lark/pkg/proto/pb_enum"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type REQUEST_ROLE int32

const (
	REQUEST_ROLE_UNKNOWN_REQUEST_ROLE REQUEST_ROLE = 0
	REQUEST_ROLE_INITIATOR            REQUEST_ROLE = 1 // 发起者
	REQUEST_ROLE_APPROVER             REQUEST_ROLE = 2 // 审批人
)

// Enum value maps for REQUEST_ROLE.
var (
	REQUEST_ROLE_name = map[int32]string{
		0: "UNKNOWN_REQUEST_ROLE",
		1: "INITIATOR",
		2: "APPROVER",
	}
	REQUEST_ROLE_value = map[string]int32{
		"UNKNOWN_REQUEST_ROLE": 0,
		"INITIATOR":            1,
		"APPROVER":             2,
	}
)

func (x REQUEST_ROLE) Enum() *REQUEST_ROLE {
	p := new(REQUEST_ROLE)
	*p = x
	return p
}

func (x REQUEST_ROLE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (REQUEST_ROLE) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_req_req_proto_enumTypes[0].Descriptor()
}

func (REQUEST_ROLE) Type() protoreflect.EnumType {
	return &file_pb_req_req_proto_enumTypes[0]
}

func (x REQUEST_ROLE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use REQUEST_ROLE.Descriptor instead.
func (REQUEST_ROLE) EnumDescriptor() ([]byte, []int) {
	return file_pb_req_req_proto_rawDescGZIP(), []int{0}
}

type REQUEST_HANDLE_RESULT int32

const (
	REQUEST_HANDLE_RESULT_UNKNOWN_HANDLE_RESULT REQUEST_HANDLE_RESULT = 0
	REQUEST_HANDLE_RESULT_ACCEPT                REQUEST_HANDLE_RESULT = 1 // 同意
	REQUEST_HANDLE_RESULT_REFUSE                REQUEST_HANDLE_RESULT = 2 // 拒绝
)

// Enum value maps for REQUEST_HANDLE_RESULT.
var (
	REQUEST_HANDLE_RESULT_name = map[int32]string{
		0: "UNKNOWN_HANDLE_RESULT",
		1: "ACCEPT",
		2: "REFUSE",
	}
	REQUEST_HANDLE_RESULT_value = map[string]int32{
		"UNKNOWN_HANDLE_RESULT": 0,
		"ACCEPT":                1,
		"REFUSE":                2,
	}
)

func (x REQUEST_HANDLE_RESULT) Enum() *REQUEST_HANDLE_RESULT {
	p := new(REQUEST_HANDLE_RESULT)
	*p = x
	return p
}

func (x REQUEST_HANDLE_RESULT) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (REQUEST_HANDLE_RESULT) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_req_req_proto_enumTypes[1].Descriptor()
}

func (REQUEST_HANDLE_RESULT) Type() protoreflect.EnumType {
	return &file_pb_req_req_proto_enumTypes[1]
}

func (x REQUEST_HANDLE_RESULT) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use REQUEST_HANDLE_RESULT.Descriptor instead.
func (REQUEST_HANDLE_RESULT) EnumDescriptor() ([]byte, []int) {
	return file_pb_req_req_proto_rawDescGZIP(), []int{1}
}

type NewChatRequestReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChatType     pb_enum.CHAT_TYPE `protobuf:"varint,1,opt,name=chat_type,json=chatType,proto3,enum=pb_enum.CHAT_TYPE" json:"chat_type,omitempty"` // 1:私聊/2:群聊
	InitiatorUid int64             `protobuf:"varint,2,opt,name=initiator_uid,json=initiatorUid,proto3" json:"initiator_uid,omitempty"`            // 发起人 UID
	TargetId     int64             `protobuf:"varint,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`                        // 被邀请人UID/群ID
	RequestMsg   string            `protobuf:"bytes,4,opt,name=request_msg,json=requestMsg,proto3" json:"request_msg,omitempty"`                   // 邀请消息
}

func (x *NewChatRequestReq) Reset() {
	*x = NewChatRequestReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_req_req_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewChatRequestReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewChatRequestReq) ProtoMessage() {}

func (x *NewChatRequestReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_req_req_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewChatRequestReq.ProtoReflect.Descriptor instead.
func (*NewChatRequestReq) Descriptor() ([]byte, []int) {
	return file_pb_req_req_proto_rawDescGZIP(), []int{0}
}

func (x *NewChatRequestReq) GetChatType() pb_enum.CHAT_TYPE {
	if x != nil {
		return x.ChatType
	}
	return pb_enum.CHAT_TYPE(0)
}

func (x *NewChatRequestReq) GetInitiatorUid() int64 {
	if x != nil {
		return x.InitiatorUid
	}
	return 0
}

func (x *NewChatRequestReq) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *NewChatRequestReq) GetRequestMsg() string {
	if x != nil {
		return x.RequestMsg
	}
	return ""
}

type NewChatRequestResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *NewChatRequestResp) Reset() {
	*x = NewChatRequestResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_req_req_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewChatRequestResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewChatRequestResp) ProtoMessage() {}

func (x *NewChatRequestResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_req_req_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewChatRequestResp.ProtoReflect.Descriptor instead.
func (*NewChatRequestResp) Descriptor() ([]byte, []int) {
	return file_pb_req_req_proto_rawDescGZIP(), []int{1}
}

func (x *NewChatRequestResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *NewChatRequestResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type ChatRequestListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid          string                `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Role         REQUEST_ROLE          `protobuf:"varint,2,opt,name=role,proto3,enum=pb_req.REQUEST_ROLE" json:"role,omitempty"` // 角色
	MaxRequestId int32                 `protobuf:"varint,3,opt,name=max_request_id,json=maxRequestId,proto3" json:"max_request_id,omitempty"`
	HandleResult REQUEST_HANDLE_RESULT `protobuf:"varint,4,opt,name=handle_result,json=handleResult,proto3,enum=pb_req.REQUEST_HANDLE_RESULT" json:"handle_result,omitempty"` // 结果
	PageSize     int32                 `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
}

func (x *ChatRequestListReq) Reset() {
	*x = ChatRequestListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_req_req_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatRequestListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequestListReq) ProtoMessage() {}

func (x *ChatRequestListReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_req_req_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequestListReq.ProtoReflect.Descriptor instead.
func (*ChatRequestListReq) Descriptor() ([]byte, []int) {
	return file_pb_req_req_proto_rawDescGZIP(), []int{2}
}

func (x *ChatRequestListReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *ChatRequestListReq) GetRole() REQUEST_ROLE {
	if x != nil {
		return x.Role
	}
	return REQUEST_ROLE_UNKNOWN_REQUEST_ROLE
}

func (x *ChatRequestListReq) GetMaxRequestId() int32 {
	if x != nil {
		return x.MaxRequestId
	}
	return 0
}

func (x *ChatRequestListReq) GetHandleResult() REQUEST_HANDLE_RESULT {
	if x != nil {
		return x.HandleResult
	}
	return REQUEST_HANDLE_RESULT_UNKNOWN_HANDLE_RESULT
}

func (x *ChatRequestListReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ChatRequestListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32              `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string             `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	List []*ChatRequestInfo `protobuf:"bytes,3,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *ChatRequestListResp) Reset() {
	*x = ChatRequestListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_req_req_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatRequestListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequestListResp) ProtoMessage() {}

func (x *ChatRequestListResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_req_req_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequestListResp.ProtoReflect.Descriptor instead.
func (*ChatRequestListResp) Descriptor() ([]byte, []int) {
	return file_pb_req_req_proto_rawDescGZIP(), []int{3}
}

func (x *ChatRequestListResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ChatRequestListResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ChatRequestListResp) GetList() []*ChatRequestInfo {
	if x != nil {
		return x.List
	}
	return nil
}

type ChatRequestInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId    int64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`                                            // request ID
	RequestTs    int64                 `protobuf:"varint,2,opt,name=request_ts,json=requestTs,proto3" json:"request_ts,omitempty"`                                            // 申请时间
	ChatType     pb_enum.CHAT_TYPE     `protobuf:"varint,3,opt,name=chat_type,json=chatType,proto3,enum=pb_enum.CHAT_TYPE" json:"chat_type,omitempty"`                        // 1:私聊/2:群聊
	InitiatorUid int64                 `protobuf:"varint,4,opt,name=initiator_uid,json=initiatorUid,proto3" json:"initiator_uid,omitempty"`                                   // 发起人 UID
	TargetId     int64                 `protobuf:"varint,5,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`                                               // 被邀请人UID/群ID
	RequestMsg   string                `protobuf:"bytes,6,opt,name=request_msg,json=requestMsg,proto3" json:"request_msg,omitempty"`                                          // request消息
	HandleResult REQUEST_HANDLE_RESULT `protobuf:"varint,7,opt,name=handle_result,json=handleResult,proto3,enum=pb_req.REQUEST_HANDLE_RESULT" json:"handle_result,omitempty"` // 结果
	HandleMsg    string                `protobuf:"bytes,8,opt,name=handle_msg,json=handleMsg,proto3" json:"handle_msg,omitempty"`                                             // 处理消息
	HandledTs    int64                 `protobuf:"varint,9,opt,name=handled_ts,json=handledTs,proto3" json:"handled_ts,omitempty"`                                            // 处理时间
}

func (x *ChatRequestInfo) Reset() {
	*x = ChatRequestInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_req_req_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatRequestInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequestInfo) ProtoMessage() {}

func (x *ChatRequestInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pb_req_req_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequestInfo.ProtoReflect.Descriptor instead.
func (*ChatRequestInfo) Descriptor() ([]byte, []int) {
	return file_pb_req_req_proto_rawDescGZIP(), []int{4}
}

func (x *ChatRequestInfo) GetRequestId() int64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *ChatRequestInfo) GetRequestTs() int64 {
	if x != nil {
		return x.RequestTs
	}
	return 0
}

func (x *ChatRequestInfo) GetChatType() pb_enum.CHAT_TYPE {
	if x != nil {
		return x.ChatType
	}
	return pb_enum.CHAT_TYPE(0)
}

func (x *ChatRequestInfo) GetInitiatorUid() int64 {
	if x != nil {
		return x.InitiatorUid
	}
	return 0
}

func (x *ChatRequestInfo) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *ChatRequestInfo) GetRequestMsg() string {
	if x != nil {
		return x.RequestMsg
	}
	return ""
}

func (x *ChatRequestInfo) GetHandleResult() REQUEST_HANDLE_RESULT {
	if x != nil {
		return x.HandleResult
	}
	return REQUEST_HANDLE_RESULT_UNKNOWN_HANDLE_RESULT
}

func (x *ChatRequestInfo) GetHandleMsg() string {
	if x != nil {
		return x.HandleMsg
	}
	return ""
}

func (x *ChatRequestInfo) GetHandledTs() int64 {
	if x != nil {
		return x.HandledTs
	}
	return 0
}

type ChatRequestHandlerReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId    int64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`                                            // request ID
	HandlerUid   int64                 `protobuf:"varint,2,opt,name=handler_uid,json=handlerUid,proto3" json:"handler_uid,omitempty"`                                         // 处理人 UID
	HandleResult REQUEST_HANDLE_RESULT `protobuf:"varint,3,opt,name=handle_result,json=handleResult,proto3,enum=pb_req.REQUEST_HANDLE_RESULT" json:"handle_result,omitempty"` // 结果
	HandleMsg    string                `protobuf:"bytes,4,opt,name=handle_msg,json=handleMsg,proto3" json:"handle_msg,omitempty"`                                             // 处理消息
}

func (x *ChatRequestHandlerReq) Reset() {
	*x = ChatRequestHandlerReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_req_req_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatRequestHandlerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequestHandlerReq) ProtoMessage() {}

func (x *ChatRequestHandlerReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_req_req_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequestHandlerReq.ProtoReflect.Descriptor instead.
func (*ChatRequestHandlerReq) Descriptor() ([]byte, []int) {
	return file_pb_req_req_proto_rawDescGZIP(), []int{5}
}

func (x *ChatRequestHandlerReq) GetRequestId() int64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *ChatRequestHandlerReq) GetHandlerUid() int64 {
	if x != nil {
		return x.HandlerUid
	}
	return 0
}

func (x *ChatRequestHandlerReq) GetHandleResult() REQUEST_HANDLE_RESULT {
	if x != nil {
		return x.HandleResult
	}
	return REQUEST_HANDLE_RESULT_UNKNOWN_HANDLE_RESULT
}

func (x *ChatRequestHandlerReq) GetHandleMsg() string {
	if x != nil {
		return x.HandleMsg
	}
	return ""
}

type ChatRequestHandlerResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *ChatRequestHandlerResp) Reset() {
	*x = ChatRequestHandlerResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_req_req_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatRequestHandlerResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequestHandlerResp) ProtoMessage() {}

func (x *ChatRequestHandlerResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_req_req_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequestHandlerResp.ProtoReflect.Descriptor instead.
func (*ChatRequestHandlerResp) Descriptor() ([]byte, []int) {
	return file_pb_req_req_proto_rawDescGZIP(), []int{6}
}

func (x *ChatRequestHandlerResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ChatRequestHandlerResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_pb_req_req_proto protoreflect.FileDescriptor

var file_pb_req_req_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x62, 0x5f, 0x72, 0x65, 0x71, 0x2f, 0x72, 0x65, 0x71, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x06, 0x70, 0x62, 0x5f, 0x72, 0x65, 0x71, 0x1a, 0x12, 0x70, 0x62, 0x5f, 0x65,
	0x6e, 0x75, 0x6d, 0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa7,
	0x01, 0x0a, 0x11, 0x4e, 0x65, 0x77, 0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x12, 0x2f, 0x0a, 0x09, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x5f, 0x65, 0x6e, 0x75,
	0x6d, 0x2e, 0x43, 0x48, 0x41, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x52, 0x08, 0x63, 0x68, 0x61,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x74,
	0x6f, 0x72, 0x5f, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x69, 0x6e,
	0x69, 0x74, 0x69, 0x61, 0x74, 0x6f, 0x72, 0x55, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x74,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x73, 0x67, 0x22, 0x3a, 0x0a, 0x12, 0x4e, 0x65, 0x77, 0x43,
	0x68, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12,
	0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6d, 0x73, 0x67, 0x22, 0xd7, 0x01, 0x0a, 0x12, 0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x28, 0x0a,
	0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x70, 0x62,
	0x5f, 0x72, 0x65, 0x71, 0x2e, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x5f, 0x52, 0x4f, 0x4c,
	0x45, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x12, 0x24, 0x0a, 0x0e, 0x6d, 0x61, 0x78, 0x5f, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0c, 0x6d, 0x61, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x42, 0x0a,
	0x0d, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x70, 0x62, 0x5f, 0x72, 0x65, 0x71, 0x2e, 0x52, 0x45,
	0x51, 0x55, 0x45, 0x53, 0x54, 0x5f, 0x48, 0x41, 0x4e, 0x44, 0x4c, 0x45, 0x5f, 0x52, 0x45, 0x53,
	0x55, 0x4c, 0x54, 0x52, 0x0c, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x68,
	0x0a, 0x13, 0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x2b, 0x0a, 0x04, 0x6c,
	0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x62, 0x5f, 0x72,
	0x65, 0x71, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0xe5, 0x02, 0x0a, 0x0f, 0x43, 0x68, 0x61,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1d, 0x0a, 0x0a,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x54, 0x73, 0x12, 0x2f, 0x0a, 0x09, 0x63, 0x68,
	0x61, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e,
	0x70, 0x62, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x43, 0x48, 0x41, 0x54, 0x5f, 0x54, 0x59, 0x50,
	0x45, 0x52, 0x08, 0x63, 0x68, 0x61, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x69,
	0x6e, 0x69, 0x74, 0x69, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x75, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0c, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x74, 0x6f, 0x72, 0x55, 0x69, 0x64,
	0x12, 0x1b, 0x0a, 0x09, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x08, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x49, 0x64, 0x12, 0x1f, 0x0a,
	0x0b, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x73, 0x67, 0x12, 0x42,
	0x0a, 0x0d, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x70, 0x62, 0x5f, 0x72, 0x65, 0x71, 0x2e, 0x52,
	0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x5f, 0x48, 0x41, 0x4e, 0x44, 0x4c, 0x45, 0x5f, 0x52, 0x45,
	0x53, 0x55, 0x4c, 0x54, 0x52, 0x0c, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x5f, 0x6d, 0x73, 0x67,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x4d, 0x73,
	0x67, 0x12, 0x1d, 0x0a, 0x0a, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x64, 0x5f, 0x74, 0x73, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x64, 0x54, 0x73,
	0x22, 0xba, 0x01, 0x0a, 0x15, 0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x68, 0x61, 0x6e,
	0x64, 0x6c, 0x65, 0x72, 0x5f, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a,
	0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x55, 0x69, 0x64, 0x12, 0x42, 0x0a, 0x0d, 0x68, 0x61,
	0x6e, 0x64, 0x6c, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x1d, 0x2e, 0x70, 0x62, 0x5f, 0x72, 0x65, 0x71, 0x2e, 0x52, 0x45, 0x51, 0x55, 0x45,
	0x53, 0x54, 0x5f, 0x48, 0x41, 0x4e, 0x44, 0x4c, 0x45, 0x5f, 0x52, 0x45, 0x53, 0x55, 0x4c, 0x54,
	0x52, 0x0c, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1d,
	0x0a, 0x0a, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x4d, 0x73, 0x67, 0x22, 0x3e, 0x0a,
	0x16, 0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x61, 0x6e, 0x64,
	0x6c, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d,
	0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x2a, 0x45, 0x0a,
	0x0c, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x5f, 0x52, 0x4f, 0x4c, 0x45, 0x12, 0x18, 0x0a,
	0x14, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54,
	0x5f, 0x52, 0x4f, 0x4c, 0x45, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x49, 0x4e, 0x49, 0x54, 0x49,
	0x41, 0x54, 0x4f, 0x52, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x41, 0x50, 0x50, 0x52, 0x4f, 0x56,
	0x45, 0x52, 0x10, 0x02, 0x2a, 0x4a, 0x0a, 0x15, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x5f,
	0x48, 0x41, 0x4e, 0x44, 0x4c, 0x45, 0x5f, 0x52, 0x45, 0x53, 0x55, 0x4c, 0x54, 0x12, 0x19, 0x0a,
	0x15, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x48, 0x41, 0x4e, 0x44, 0x4c, 0x45, 0x5f,
	0x52, 0x45, 0x53, 0x55, 0x4c, 0x54, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x43, 0x43, 0x45,
	0x50, 0x54, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x52, 0x45, 0x46, 0x55, 0x53, 0x45, 0x10, 0x02,
	0x32, 0xf3, 0x01, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x47, 0x0a, 0x0e,
	0x4e, 0x65, 0x77, 0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19,
	0x2e, 0x70, 0x62, 0x5f, 0x72, 0x65, 0x71, 0x2e, 0x4e, 0x65, 0x77, 0x43, 0x68, 0x61, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e, 0x70, 0x62, 0x5f, 0x72,
	0x65, 0x71, 0x2e, 0x4e, 0x65, 0x77, 0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x4a, 0x0a, 0x0f, 0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1a, 0x2e, 0x70, 0x62, 0x5f, 0x72, 0x65,
	0x71, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x70, 0x62, 0x5f, 0x72, 0x65, 0x71, 0x2e, 0x43, 0x68,
	0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x53, 0x0a, 0x12, 0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x12, 0x1d, 0x2e, 0x70, 0x62, 0x5f, 0x72, 0x65, 0x71,
	0x2e, 0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x61, 0x6e, 0x64,
	0x6c, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x1e, 0x2e, 0x70, 0x62, 0x5f, 0x72, 0x65, 0x71, 0x2e,
	0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x61, 0x6e, 0x64, 0x6c,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x42, 0x11, 0x5a, 0x0f, 0x2e, 0x2f, 0x70, 0x62, 0x5f, 0x72,
	0x65, 0x71, 0x3b, 0x70, 0x62, 0x5f, 0x72, 0x65, 0x71, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_pb_req_req_proto_rawDescOnce sync.Once
	file_pb_req_req_proto_rawDescData = file_pb_req_req_proto_rawDesc
)

func file_pb_req_req_proto_rawDescGZIP() []byte {
	file_pb_req_req_proto_rawDescOnce.Do(func() {
		file_pb_req_req_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_req_req_proto_rawDescData)
	})
	return file_pb_req_req_proto_rawDescData
}

var file_pb_req_req_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pb_req_req_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pb_req_req_proto_goTypes = []interface{}{
	(REQUEST_ROLE)(0),              // 0: pb_req.REQUEST_ROLE
	(REQUEST_HANDLE_RESULT)(0),     // 1: pb_req.REQUEST_HANDLE_RESULT
	(*NewChatRequestReq)(nil),      // 2: pb_req.NewChatRequestReq
	(*NewChatRequestResp)(nil),     // 3: pb_req.NewChatRequestResp
	(*ChatRequestListReq)(nil),     // 4: pb_req.ChatRequestListReq
	(*ChatRequestListResp)(nil),    // 5: pb_req.ChatRequestListResp
	(*ChatRequestInfo)(nil),        // 6: pb_req.ChatRequestInfo
	(*ChatRequestHandlerReq)(nil),  // 7: pb_req.ChatRequestHandlerReq
	(*ChatRequestHandlerResp)(nil), // 8: pb_req.ChatRequestHandlerResp
	(pb_enum.CHAT_TYPE)(0),         // 9: pb_enum.CHAT_TYPE
}
var file_pb_req_req_proto_depIdxs = []int32{
	9,  // 0: pb_req.NewChatRequestReq.chat_type:type_name -> pb_enum.CHAT_TYPE
	0,  // 1: pb_req.ChatRequestListReq.role:type_name -> pb_req.REQUEST_ROLE
	1,  // 2: pb_req.ChatRequestListReq.handle_result:type_name -> pb_req.REQUEST_HANDLE_RESULT
	6,  // 3: pb_req.ChatRequestListResp.list:type_name -> pb_req.ChatRequestInfo
	9,  // 4: pb_req.ChatRequestInfo.chat_type:type_name -> pb_enum.CHAT_TYPE
	1,  // 5: pb_req.ChatRequestInfo.handle_result:type_name -> pb_req.REQUEST_HANDLE_RESULT
	1,  // 6: pb_req.ChatRequestHandlerReq.handle_result:type_name -> pb_req.REQUEST_HANDLE_RESULT
	2,  // 7: pb_req.Request.NewChatRequest:input_type -> pb_req.NewChatRequestReq
	4,  // 8: pb_req.Request.ChatRequestList:input_type -> pb_req.ChatRequestListReq
	7,  // 9: pb_req.Request.ChatRequestHandler:input_type -> pb_req.ChatRequestHandlerReq
	3,  // 10: pb_req.Request.NewChatRequest:output_type -> pb_req.NewChatRequestResp
	5,  // 11: pb_req.Request.ChatRequestList:output_type -> pb_req.ChatRequestListResp
	8,  // 12: pb_req.Request.ChatRequestHandler:output_type -> pb_req.ChatRequestHandlerResp
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_pb_req_req_proto_init() }
func file_pb_req_req_proto_init() {
	if File_pb_req_req_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_req_req_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewChatRequestReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_req_req_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewChatRequestResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_req_req_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatRequestListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_req_req_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatRequestListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_req_req_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatRequestInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_req_req_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatRequestHandlerReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_req_req_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatRequestHandlerResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_req_req_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_req_req_proto_goTypes,
		DependencyIndexes: file_pb_req_req_proto_depIdxs,
		EnumInfos:         file_pb_req_req_proto_enumTypes,
		MessageInfos:      file_pb_req_req_proto_msgTypes,
	}.Build()
	File_pb_req_req_proto = out.File
	file_pb_req_req_proto_rawDesc = nil
	file_pb_req_req_proto_goTypes = nil
	file_pb_req_req_proto_depIdxs = nil
}
