// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: pb_mq/mq.proto

package pb_mq

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	pb_enum "lark/pkg/proto/pb_enum"
	pb_msg "lark/pkg/proto/pb_msg"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InboxMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Topic    pb_enum.TOPIC          `protobuf:"varint,1,opt,name=topic,proto3,enum=pb_enum.TOPIC" json:"topic,omitempty"`
	SubTopic pb_enum.SUB_TOPIC      `protobuf:"varint,2,opt,name=sub_topic,json=subTopic,proto3,enum=pb_enum.SUB_TOPIC" json:"sub_topic,omitempty"`
	Msg      *pb_msg.SrvChatMessage `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *InboxMessage) Reset() {
	*x = InboxMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_mq_mq_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InboxMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InboxMessage) ProtoMessage() {}

func (x *InboxMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pb_mq_mq_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InboxMessage.ProtoReflect.Descriptor instead.
func (*InboxMessage) Descriptor() ([]byte, []int) {
	return file_pb_mq_mq_proto_rawDescGZIP(), []int{0}
}

func (x *InboxMessage) GetTopic() pb_enum.TOPIC {
	if x != nil {
		return x.Topic
	}
	return pb_enum.TOPIC(0)
}

func (x *InboxMessage) GetSubTopic() pb_enum.SUB_TOPIC {
	if x != nil {
		return x.SubTopic
	}
	return pb_enum.SUB_TOPIC(0)
}

func (x *InboxMessage) GetMsg() *pb_msg.SrvChatMessage {
	if x != nil {
		return x.Msg
	}
	return nil
}

type UserOnline struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid      int64                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Platform pb_enum.PLATFORM_TYPE `protobuf:"varint,2,opt,name=platform,proto3,enum=pb_enum.PLATFORM_TYPE" json:"platform,omitempty"`
	ServerId int32                 `protobuf:"varint,3,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
}

func (x *UserOnline) Reset() {
	*x = UserOnline{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_mq_mq_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserOnline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOnline) ProtoMessage() {}

func (x *UserOnline) ProtoReflect() protoreflect.Message {
	mi := &file_pb_mq_mq_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOnline.ProtoReflect.Descriptor instead.
func (*UserOnline) Descriptor() ([]byte, []int) {
	return file_pb_mq_mq_proto_rawDescGZIP(), []int{1}
}

func (x *UserOnline) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *UserOnline) GetPlatform() pb_enum.PLATFORM_TYPE {
	if x != nil {
		return x.Platform
	}
	return pb_enum.PLATFORM_TYPE(0)
}

func (x *UserOnline) GetServerId() int32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

var File_pb_mq_mq_proto protoreflect.FileDescriptor

var file_pb_mq_mq_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x62, 0x5f, 0x6d, 0x71, 0x2f, 0x6d, 0x71, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x05, 0x70, 0x62, 0x5f, 0x6d, 0x71, 0x1a, 0x12, 0x70, 0x62, 0x5f, 0x65, 0x6e, 0x75, 0x6d,
	0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x10, 0x70, 0x62, 0x5f,
	0x6d, 0x73, 0x67, 0x2f, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8f, 0x01,
	0x0a, 0x0c, 0x49, 0x6e, 0x62, 0x6f, 0x78, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x24,
	0x0a, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e,
	0x70, 0x62, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x54, 0x4f, 0x50, 0x49, 0x43, 0x52, 0x05, 0x74,
	0x6f, 0x70, 0x69, 0x63, 0x12, 0x2f, 0x0a, 0x09, 0x73, 0x75, 0x62, 0x5f, 0x74, 0x6f, 0x70, 0x69,
	0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x5f, 0x65, 0x6e, 0x75,
	0x6d, 0x2e, 0x53, 0x55, 0x42, 0x5f, 0x54, 0x4f, 0x50, 0x49, 0x43, 0x52, 0x08, 0x73, 0x75, 0x62,
	0x54, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x28, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x62, 0x5f, 0x6d, 0x73, 0x67, 0x2e, 0x53, 0x72, 0x76, 0x43,
	0x68, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22,
	0x6f, 0x0a, 0x0a, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12,
	0x32, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x16, 0x2e, 0x70, 0x62, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x50, 0x4c, 0x41, 0x54,
	0x46, 0x4f, 0x52, 0x4d, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66,
	0x6f, 0x72, 0x6d, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64,
	0x42, 0x1c, 0x5a, 0x1a, 0x6c, 0x61, 0x72, 0x6b, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x70, 0x62, 0x5f, 0x6d, 0x71, 0x3b, 0x70, 0x62, 0x5f, 0x6d, 0x71, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_mq_mq_proto_rawDescOnce sync.Once
	file_pb_mq_mq_proto_rawDescData = file_pb_mq_mq_proto_rawDesc
)

func file_pb_mq_mq_proto_rawDescGZIP() []byte {
	file_pb_mq_mq_proto_rawDescOnce.Do(func() {
		file_pb_mq_mq_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_mq_mq_proto_rawDescData)
	})
	return file_pb_mq_mq_proto_rawDescData
}

var file_pb_mq_mq_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_mq_mq_proto_goTypes = []interface{}{
	(*InboxMessage)(nil),          // 0: pb_mq.InboxMessage
	(*UserOnline)(nil),            // 1: pb_mq.UserOnline
	(pb_enum.TOPIC)(0),            // 2: pb_enum.TOPIC
	(pb_enum.SUB_TOPIC)(0),        // 3: pb_enum.SUB_TOPIC
	(*pb_msg.SrvChatMessage)(nil), // 4: pb_msg.SrvChatMessage
	(pb_enum.PLATFORM_TYPE)(0),    // 5: pb_enum.PLATFORM_TYPE
}
var file_pb_mq_mq_proto_depIdxs = []int32{
	2, // 0: pb_mq.InboxMessage.topic:type_name -> pb_enum.TOPIC
	3, // 1: pb_mq.InboxMessage.sub_topic:type_name -> pb_enum.SUB_TOPIC
	4, // 2: pb_mq.InboxMessage.msg:type_name -> pb_msg.SrvChatMessage
	5, // 3: pb_mq.UserOnline.platform:type_name -> pb_enum.PLATFORM_TYPE
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pb_mq_mq_proto_init() }
func file_pb_mq_mq_proto_init() {
	if File_pb_mq_mq_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_mq_mq_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InboxMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_mq_mq_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserOnline); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_mq_mq_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_mq_mq_proto_goTypes,
		DependencyIndexes: file_pb_mq_mq_proto_depIdxs,
		MessageInfos:      file_pb_mq_mq_proto_msgTypes,
	}.Build()
	File_pb_mq_mq_proto = out.File
	file_pb_mq_mq_proto_rawDesc = nil
	file_pb_mq_mq_proto_goTypes = nil
	file_pb_mq_mq_proto_depIdxs = nil
}
