package service

const (
	ERROR_CODE_PUSH_PROTOCOL_UNMARSHAL_ERR int32 = 90001
	ERROR_CODE_PUSH_GRPC_SERVICE_FAILURE   int32 = 90002 // 服务故障
)

const (
	ERROR_PUSH_PROTOCOL_UNMARSHAL_ERR = "协议反序列化错误"
	ERROR_PUSH_GRPC_SERVICE_FAILURE   = "服务故障"
)
