// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: pb_wallet/wallet.proto

package pb_wallet

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "lark/pkg/proto/pb_enum"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WALLET_TYPE int32

const (
	WALLET_TYPE_UNKNOWN_WALLET_TYPE WALLET_TYPE = 0
	WALLET_TYPE_CURRENCY            WALLET_TYPE = 1 // 货币 单位(分)
	WALLET_TYPE_DIAMOND             WALLET_TYPE = 2 // 砖石
	WALLET_TYPE_GOLD_COIN           WALLET_TYPE = 3 // 金币
	WALLET_TYPE_SILVER_COIN         WALLET_TYPE = 4 // 银币
	WALLET_TYPE_BRONZE_COIN         WALLET_TYPE = 5 // 铜币
	WALLET_TYPE_POINT               WALLET_TYPE = 6 // 积分
)

// Enum value maps for WALLET_TYPE.
var (
	WALLET_TYPE_name = map[int32]string{
		0: "UNKNOWN_WALLET_TYPE",
		1: "CURRENCY",
		2: "DIAMOND",
		3: "GOLD_COIN",
		4: "SILVER_COIN",
		5: "BRONZE_COIN",
		6: "POINT",
	}
	WALLET_TYPE_value = map[string]int32{
		"UNKNOWN_WALLET_TYPE": 0,
		"CURRENCY":            1,
		"DIAMOND":             2,
		"GOLD_COIN":           3,
		"SILVER_COIN":         4,
		"BRONZE_COIN":         5,
		"POINT":               6,
	}
)

func (x WALLET_TYPE) Enum() *WALLET_TYPE {
	p := new(WALLET_TYPE)
	*p = x
	return p
}

func (x WALLET_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WALLET_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_wallet_wallet_proto_enumTypes[0].Descriptor()
}

func (WALLET_TYPE) Type() protoreflect.EnumType {
	return &file_pb_wallet_wallet_proto_enumTypes[0]
}

func (x WALLET_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WALLET_TYPE.Descriptor instead.
func (WALLET_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_pb_wallet_wallet_proto_rawDescGZIP(), []int{0}
}

//查询余额
type CheckBalanceReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid int64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *CheckBalanceReq) Reset() {
	*x = CheckBalanceReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_wallet_wallet_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckBalanceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckBalanceReq) ProtoMessage() {}

func (x *CheckBalanceReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_wallet_wallet_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckBalanceReq.ProtoReflect.Descriptor instead.
func (*CheckBalanceReq) Descriptor() ([]byte, []int) {
	return file_pb_wallet_wallet_proto_rawDescGZIP(), []int{0}
}

func (x *CheckBalanceReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type CheckBalanceResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code     int32            `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg      string           `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Balances []*WalletBalance `protobuf:"bytes,3,rep,name=balances,proto3" json:"balances,omitempty"`
}

func (x *CheckBalanceResp) Reset() {
	*x = CheckBalanceResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_wallet_wallet_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckBalanceResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckBalanceResp) ProtoMessage() {}

func (x *CheckBalanceResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_wallet_wallet_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckBalanceResp.ProtoReflect.Descriptor instead.
func (*CheckBalanceResp) Descriptor() ([]byte, []int) {
	return file_pb_wallet_wallet_proto_rawDescGZIP(), []int{1}
}

func (x *CheckBalanceResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CheckBalanceResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *CheckBalanceResp) GetBalances() []*WalletBalance {
	if x != nil {
		return x.Balances
	}
	return nil
}

type WalletBalance struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId  int64       `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	WalletType WALLET_TYPE `protobuf:"varint,2,opt,name=wallet_type,json=walletType,proto3,enum=pb_wallet.WALLET_TYPE" json:"wallet_type,omitempty"`
	Balances   int64       `protobuf:"varint,3,opt,name=balances,proto3" json:"balances,omitempty"`
}

func (x *WalletBalance) Reset() {
	*x = WalletBalance{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_wallet_wallet_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WalletBalance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletBalance) ProtoMessage() {}

func (x *WalletBalance) ProtoReflect() protoreflect.Message {
	mi := &file_pb_wallet_wallet_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletBalance.ProtoReflect.Descriptor instead.
func (*WalletBalance) Descriptor() ([]byte, []int) {
	return file_pb_wallet_wallet_proto_rawDescGZIP(), []int{2}
}

func (x *WalletBalance) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *WalletBalance) GetWalletType() WALLET_TYPE {
	if x != nil {
		return x.WalletType
	}
	return WALLET_TYPE_UNKNOWN_WALLET_TYPE
}

func (x *WalletBalance) GetBalances() int64 {
	if x != nil {
		return x.Balances
	}
	return 0
}

//兑换
type ExchangeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid    int64       `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	From   WALLET_TYPE `protobuf:"varint,2,opt,name=from,proto3,enum=pb_wallet.WALLET_TYPE" json:"from,omitempty"`
	To     WALLET_TYPE `protobuf:"varint,3,opt,name=to,proto3,enum=pb_wallet.WALLET_TYPE" json:"to,omitempty"`
	Amount int64       `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"` // from的数量
}

func (x *ExchangeReq) Reset() {
	*x = ExchangeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_wallet_wallet_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExchangeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeReq) ProtoMessage() {}

func (x *ExchangeReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_wallet_wallet_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeReq.ProtoReflect.Descriptor instead.
func (*ExchangeReq) Descriptor() ([]byte, []int) {
	return file_pb_wallet_wallet_proto_rawDescGZIP(), []int{3}
}

func (x *ExchangeReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ExchangeReq) GetFrom() WALLET_TYPE {
	if x != nil {
		return x.From
	}
	return WALLET_TYPE_UNKNOWN_WALLET_TYPE
}

func (x *ExchangeReq) GetTo() WALLET_TYPE {
	if x != nil {
		return x.To
	}
	return WALLET_TYPE_UNKNOWN_WALLET_TYPE
}

func (x *ExchangeReq) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type ExchangeResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid      int64       `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	From     WALLET_TYPE `protobuf:"varint,2,opt,name=from,proto3,enum=pb_wallet.WALLET_TYPE" json:"from,omitempty"`
	To       WALLET_TYPE `protobuf:"varint,3,opt,name=to,proto3,enum=pb_wallet.WALLET_TYPE" json:"to,omitempty"`
	Quantity int64       `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"` // 兑换金额
}

func (x *ExchangeResp) Reset() {
	*x = ExchangeResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_wallet_wallet_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExchangeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeResp) ProtoMessage() {}

func (x *ExchangeResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_wallet_wallet_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeResp.ProtoReflect.Descriptor instead.
func (*ExchangeResp) Descriptor() ([]byte, []int) {
	return file_pb_wallet_wallet_proto_rawDescGZIP(), []int{4}
}

func (x *ExchangeResp) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ExchangeResp) GetFrom() WALLET_TYPE {
	if x != nil {
		return x.From
	}
	return WALLET_TYPE_UNKNOWN_WALLET_TYPE
}

func (x *ExchangeResp) GetTo() WALLET_TYPE {
	if x != nil {
		return x.To
	}
	return WALLET_TYPE_UNKNOWN_WALLET_TYPE
}

func (x *ExchangeResp) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

//转账
type TransferReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WalletType WALLET_TYPE `protobuf:"varint,1,opt,name=wallet_type,json=walletType,proto3,enum=pb_wallet.WALLET_TYPE" json:"wallet_type,omitempty"`
	FromUid    int64       `protobuf:"varint,2,opt,name=from_uid,json=fromUid,proto3" json:"from_uid,omitempty"`
	ToUid      int64       `protobuf:"varint,3,opt,name=to_uid,json=toUid,proto3" json:"to_uid,omitempty"`
	Amount     int64       `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"` // 转账金额
}

func (x *TransferReq) Reset() {
	*x = TransferReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_wallet_wallet_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransferReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferReq) ProtoMessage() {}

func (x *TransferReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_wallet_wallet_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferReq.ProtoReflect.Descriptor instead.
func (*TransferReq) Descriptor() ([]byte, []int) {
	return file_pb_wallet_wallet_proto_rawDescGZIP(), []int{5}
}

func (x *TransferReq) GetWalletType() WALLET_TYPE {
	if x != nil {
		return x.WalletType
	}
	return WALLET_TYPE_UNKNOWN_WALLET_TYPE
}

func (x *TransferReq) GetFromUid() int64 {
	if x != nil {
		return x.FromUid
	}
	return 0
}

func (x *TransferReq) GetToUid() int64 {
	if x != nil {
		return x.ToUid
	}
	return 0
}

func (x *TransferReq) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type TransferResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WalletType WALLET_TYPE `protobuf:"varint,1,opt,name=wallet_type,json=walletType,proto3,enum=pb_wallet.WALLET_TYPE" json:"wallet_type,omitempty"`
	FromUid    int64       `protobuf:"varint,2,opt,name=from_uid,json=fromUid,proto3" json:"from_uid,omitempty"`
	ToUid      int64       `protobuf:"varint,3,opt,name=to_uid,json=toUid,proto3" json:"to_uid,omitempty"`
	Amount     int64       `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"` // 转账金额
}

func (x *TransferResp) Reset() {
	*x = TransferResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_wallet_wallet_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransferResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferResp) ProtoMessage() {}

func (x *TransferResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_wallet_wallet_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferResp.ProtoReflect.Descriptor instead.
func (*TransferResp) Descriptor() ([]byte, []int) {
	return file_pb_wallet_wallet_proto_rawDescGZIP(), []int{6}
}

func (x *TransferResp) GetWalletType() WALLET_TYPE {
	if x != nil {
		return x.WalletType
	}
	return WALLET_TYPE_UNKNOWN_WALLET_TYPE
}

func (x *TransferResp) GetFromUid() int64 {
	if x != nil {
		return x.FromUid
	}
	return 0
}

func (x *TransferResp) GetToUid() int64 {
	if x != nil {
		return x.ToUid
	}
	return 0
}

func (x *TransferResp) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

//充值
type RechargeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid        int64       `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	WalletType WALLET_TYPE `protobuf:"varint,2,opt,name=wallet_type,json=walletType,proto3,enum=pb_wallet.WALLET_TYPE" json:"wallet_type,omitempty"`
	Amount     int64       `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"` // 金额
}

func (x *RechargeReq) Reset() {
	*x = RechargeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_wallet_wallet_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RechargeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RechargeReq) ProtoMessage() {}

func (x *RechargeReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_wallet_wallet_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RechargeReq.ProtoReflect.Descriptor instead.
func (*RechargeReq) Descriptor() ([]byte, []int) {
	return file_pb_wallet_wallet_proto_rawDescGZIP(), []int{7}
}

func (x *RechargeReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *RechargeReq) GetWalletType() WALLET_TYPE {
	if x != nil {
		return x.WalletType
	}
	return WALLET_TYPE_UNKNOWN_WALLET_TYPE
}

func (x *RechargeReq) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type RechargeResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WalletType WALLET_TYPE `protobuf:"varint,1,opt,name=wallet_type,json=walletType,proto3,enum=pb_wallet.WALLET_TYPE" json:"wallet_type,omitempty"`
	TradeNo    string      `protobuf:"bytes,2,opt,name=trade_no,json=tradeNo,proto3" json:"trade_no,omitempty"`       // 订单id
	Amount     int64       `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`                       // 金额
	Partnerid  string      `protobuf:"bytes,4,opt,name=partnerid,proto3" json:"partnerid,omitempty"`                  // 商家id
	Prepayid   string      `protobuf:"bytes,5,opt,name=prepayid,proto3" json:"prepayid,omitempty"`                    //
	Noncestr   string      `protobuf:"bytes,6,opt,name=noncestr,proto3" json:"noncestr,omitempty"`                    // 随机编码
	Timestamp  int64       `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                 // 后台生成的时间戳
	Sign       string      `protobuf:"bytes,8,opt,name=sign,proto3" json:"sign,omitempty"`                            // 签名
	NotifyUrl  string      `protobuf:"bytes,9,opt,name=notify_url,json=notifyUrl,proto3" json:"notify_url,omitempty"` //回调URL
}

func (x *RechargeResp) Reset() {
	*x = RechargeResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_wallet_wallet_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RechargeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RechargeResp) ProtoMessage() {}

func (x *RechargeResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_wallet_wallet_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RechargeResp.ProtoReflect.Descriptor instead.
func (*RechargeResp) Descriptor() ([]byte, []int) {
	return file_pb_wallet_wallet_proto_rawDescGZIP(), []int{8}
}

func (x *RechargeResp) GetWalletType() WALLET_TYPE {
	if x != nil {
		return x.WalletType
	}
	return WALLET_TYPE_UNKNOWN_WALLET_TYPE
}

func (x *RechargeResp) GetTradeNo() string {
	if x != nil {
		return x.TradeNo
	}
	return ""
}

func (x *RechargeResp) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *RechargeResp) GetPartnerid() string {
	if x != nil {
		return x.Partnerid
	}
	return ""
}

func (x *RechargeResp) GetPrepayid() string {
	if x != nil {
		return x.Prepayid
	}
	return ""
}

func (x *RechargeResp) GetNoncestr() string {
	if x != nil {
		return x.Noncestr
	}
	return ""
}

func (x *RechargeResp) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *RechargeResp) GetSign() string {
	if x != nil {
		return x.Sign
	}
	return ""
}

func (x *RechargeResp) GetNotifyUrl() string {
	if x != nil {
		return x.NotifyUrl
	}
	return ""
}

var File_pb_wallet_wallet_proto protoreflect.FileDescriptor

var file_pb_wallet_wallet_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x62, 0x5f, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x2f, 0x77, 0x61, 0x6c, 0x6c,
	0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x70, 0x62, 0x5f, 0x77, 0x61, 0x6c,
	0x6c, 0x65, 0x74, 0x1a, 0x12, 0x70, 0x62, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x2f, 0x65, 0x6e, 0x75,
	0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x23, 0x0a, 0x0f, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x6e, 0x0a, 0x10,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x34, 0x0a, 0x08, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63,
	0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x62, 0x5f, 0x77, 0x61,
	0x6c, 0x6c, 0x65, 0x74, 0x2e, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x42, 0x61, 0x6c, 0x61, 0x6e,
	0x63, 0x65, 0x52, 0x08, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x22, 0x83, 0x01, 0x0a,
	0x0d, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x1d,
	0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x37, 0x0a,
	0x0b, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x16, 0x2e, 0x70, 0x62, 0x5f, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x2e, 0x57,
	0x41, 0x4c, 0x4c, 0x45, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x52, 0x0a, 0x77, 0x61, 0x6c, 0x6c,
	0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63,
	0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63,
	0x65, 0x73, 0x22, 0x8b, 0x01, 0x0a, 0x0b, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52,
	0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x03, 0x75, 0x69, 0x64, 0x12, 0x2a, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x16, 0x2e, 0x70, 0x62, 0x5f, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x2e, 0x57,
	0x41, 0x4c, 0x4c, 0x45, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d,
	0x12, 0x26, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x70,
	0x62, 0x5f, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x2e, 0x57, 0x41, 0x4c, 0x4c, 0x45, 0x54, 0x5f,
	0x54, 0x59, 0x50, 0x45, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x22, 0x90, 0x01, 0x0a, 0x0c, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03,
	0x75, 0x69, 0x64, 0x12, 0x2a, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x16, 0x2e, 0x70, 0x62, 0x5f, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x2e, 0x57, 0x41,
	0x4c, 0x4c, 0x45, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12,
	0x26, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x70, 0x62,
	0x5f, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x2e, 0x57, 0x41, 0x4c, 0x4c, 0x45, 0x54, 0x5f, 0x54,
	0x59, 0x50, 0x45, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x22, 0x90, 0x01, 0x0a, 0x0b, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x12, 0x37, 0x0a, 0x0b, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x70, 0x62, 0x5f, 0x77, 0x61,
	0x6c, 0x6c, 0x65, 0x74, 0x2e, 0x57, 0x41, 0x4c, 0x4c, 0x45, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45,
	0x52, 0x0a, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x08,
	0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07,
	0x66, 0x72, 0x6f, 0x6d, 0x55, 0x69, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x74, 0x6f, 0x5f, 0x75, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x55, 0x69, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x91, 0x01, 0x0a, 0x0c, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x66, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x37, 0x0a, 0x0b, 0x77, 0x61, 0x6c, 0x6c, 0x65,
	0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x70,
	0x62, 0x5f, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x2e, 0x57, 0x41, 0x4c, 0x4c, 0x45, 0x54, 0x5f,
	0x54, 0x59, 0x50, 0x45, 0x52, 0x0a, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x19, 0x0a, 0x08, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x07, 0x66, 0x72, 0x6f, 0x6d, 0x55, 0x69, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x74,
	0x6f, 0x5f, 0x75, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x55,
	0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x70, 0x0a, 0x0b, 0x52, 0x65,
	0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x37, 0x0a, 0x0b, 0x77,
	0x61, 0x6c, 0x6c, 0x65, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x16, 0x2e, 0x70, 0x62, 0x5f, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x2e, 0x57, 0x41, 0x4c,
	0x4c, 0x45, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x52, 0x0a, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0xa1, 0x02, 0x0a,
	0x0c, 0x52, 0x65, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x37, 0x0a,
	0x0b, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x16, 0x2e, 0x70, 0x62, 0x5f, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x2e, 0x57,
	0x41, 0x4c, 0x4c, 0x45, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x52, 0x0a, 0x77, 0x61, 0x6c, 0x6c,
	0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x72, 0x61, 0x64, 0x65, 0x5f,
	0x6e, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x72, 0x61, 0x64, 0x65, 0x4e,
	0x6f, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x61, 0x72,
	0x74, 0x6e, 0x65, 0x72, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x61,
	0x72, 0x74, 0x6e, 0x65, 0x72, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x65, 0x70, 0x61,
	0x79, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x65, 0x70, 0x61,
	0x79, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x73, 0x74, 0x72, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x73, 0x74, 0x72, 0x12,
	0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x12, 0x0a,
	0x04, 0x73, 0x69, 0x67, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x69, 0x67,
	0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x5f, 0x75, 0x72, 0x6c, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x55, 0x72, 0x6c,
	0x2a, 0x7d, 0x0a, 0x0b, 0x57, 0x41, 0x4c, 0x4c, 0x45, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x12,
	0x17, 0x0a, 0x13, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x57, 0x41, 0x4c, 0x4c, 0x45,
	0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x43, 0x55, 0x52, 0x52,
	0x45, 0x4e, 0x43, 0x59, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x44, 0x49, 0x41, 0x4d, 0x4f, 0x4e,
	0x44, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x47, 0x4f, 0x4c, 0x44, 0x5f, 0x43, 0x4f, 0x49, 0x4e,
	0x10, 0x03, 0x12, 0x0f, 0x0a, 0x0b, 0x53, 0x49, 0x4c, 0x56, 0x45, 0x52, 0x5f, 0x43, 0x4f, 0x49,
	0x4e, 0x10, 0x04, 0x12, 0x0f, 0x0a, 0x0b, 0x42, 0x52, 0x4f, 0x4e, 0x5a, 0x45, 0x5f, 0x43, 0x4f,
	0x49, 0x4e, 0x10, 0x05, 0x12, 0x09, 0x0a, 0x05, 0x50, 0x4f, 0x49, 0x4e, 0x54, 0x10, 0x06, 0x32,
	0x88, 0x02, 0x0a, 0x06, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x12, 0x47, 0x0a, 0x0c, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x1a, 0x2e, 0x70, 0x62, 0x5f,
	0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x42, 0x61, 0x6c, 0x61,
	0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x70, 0x62, 0x5f, 0x77, 0x61, 0x6c, 0x6c,
	0x65, 0x74, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x3b, 0x0a, 0x08, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12,
	0x16, 0x2e, 0x70, 0x62, 0x5f, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x2e, 0x45, 0x78, 0x63, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x70, 0x62, 0x5f, 0x77, 0x61, 0x6c,
	0x6c, 0x65, 0x74, 0x2e, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x3b, 0x0a, 0x08, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x12, 0x16, 0x2e, 0x70,
	0x62, 0x5f, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x70, 0x62, 0x5f, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74,
	0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3b, 0x0a,
	0x08, 0x52, 0x65, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x12, 0x16, 0x2e, 0x70, 0x62, 0x5f, 0x77,
	0x61, 0x6c, 0x6c, 0x65, 0x74, 0x2e, 0x52, 0x65, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x52, 0x65,
	0x71, 0x1a, 0x17, 0x2e, 0x70, 0x62, 0x5f, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x2e, 0x52, 0x65,
	0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x42, 0x17, 0x5a, 0x15, 0x2e, 0x2f,
	0x70, 0x62, 0x5f, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x3b, 0x70, 0x62, 0x5f, 0x77, 0x61, 0x6c,
	0x6c, 0x65, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_wallet_wallet_proto_rawDescOnce sync.Once
	file_pb_wallet_wallet_proto_rawDescData = file_pb_wallet_wallet_proto_rawDesc
)

func file_pb_wallet_wallet_proto_rawDescGZIP() []byte {
	file_pb_wallet_wallet_proto_rawDescOnce.Do(func() {
		file_pb_wallet_wallet_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_wallet_wallet_proto_rawDescData)
	})
	return file_pb_wallet_wallet_proto_rawDescData
}

var file_pb_wallet_wallet_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pb_wallet_wallet_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pb_wallet_wallet_proto_goTypes = []interface{}{
	(WALLET_TYPE)(0),         // 0: pb_wallet.WALLET_TYPE
	(*CheckBalanceReq)(nil),  // 1: pb_wallet.CheckBalanceReq
	(*CheckBalanceResp)(nil), // 2: pb_wallet.CheckBalanceResp
	(*WalletBalance)(nil),    // 3: pb_wallet.WalletBalance
	(*ExchangeReq)(nil),      // 4: pb_wallet.ExchangeReq
	(*ExchangeResp)(nil),     // 5: pb_wallet.ExchangeResp
	(*TransferReq)(nil),      // 6: pb_wallet.TransferReq
	(*TransferResp)(nil),     // 7: pb_wallet.TransferResp
	(*RechargeReq)(nil),      // 8: pb_wallet.RechargeReq
	(*RechargeResp)(nil),     // 9: pb_wallet.RechargeResp
}
var file_pb_wallet_wallet_proto_depIdxs = []int32{
	3,  // 0: pb_wallet.CheckBalanceResp.balances:type_name -> pb_wallet.WalletBalance
	0,  // 1: pb_wallet.WalletBalance.wallet_type:type_name -> pb_wallet.WALLET_TYPE
	0,  // 2: pb_wallet.ExchangeReq.from:type_name -> pb_wallet.WALLET_TYPE
	0,  // 3: pb_wallet.ExchangeReq.to:type_name -> pb_wallet.WALLET_TYPE
	0,  // 4: pb_wallet.ExchangeResp.from:type_name -> pb_wallet.WALLET_TYPE
	0,  // 5: pb_wallet.ExchangeResp.to:type_name -> pb_wallet.WALLET_TYPE
	0,  // 6: pb_wallet.TransferReq.wallet_type:type_name -> pb_wallet.WALLET_TYPE
	0,  // 7: pb_wallet.TransferResp.wallet_type:type_name -> pb_wallet.WALLET_TYPE
	0,  // 8: pb_wallet.RechargeReq.wallet_type:type_name -> pb_wallet.WALLET_TYPE
	0,  // 9: pb_wallet.RechargeResp.wallet_type:type_name -> pb_wallet.WALLET_TYPE
	1,  // 10: pb_wallet.Wallet.CheckBalance:input_type -> pb_wallet.CheckBalanceReq
	4,  // 11: pb_wallet.Wallet.Exchange:input_type -> pb_wallet.ExchangeReq
	6,  // 12: pb_wallet.Wallet.Transfer:input_type -> pb_wallet.TransferReq
	8,  // 13: pb_wallet.Wallet.Recharge:input_type -> pb_wallet.RechargeReq
	2,  // 14: pb_wallet.Wallet.CheckBalance:output_type -> pb_wallet.CheckBalanceResp
	5,  // 15: pb_wallet.Wallet.Exchange:output_type -> pb_wallet.ExchangeResp
	7,  // 16: pb_wallet.Wallet.Transfer:output_type -> pb_wallet.TransferResp
	9,  // 17: pb_wallet.Wallet.Recharge:output_type -> pb_wallet.RechargeResp
	14, // [14:18] is the sub-list for method output_type
	10, // [10:14] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_pb_wallet_wallet_proto_init() }
func file_pb_wallet_wallet_proto_init() {
	if File_pb_wallet_wallet_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_wallet_wallet_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckBalanceReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_wallet_wallet_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckBalanceResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_wallet_wallet_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WalletBalance); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_wallet_wallet_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExchangeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_wallet_wallet_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExchangeResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_wallet_wallet_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransferReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_wallet_wallet_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransferResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_wallet_wallet_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RechargeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_wallet_wallet_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RechargeResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_wallet_wallet_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_wallet_wallet_proto_goTypes,
		DependencyIndexes: file_pb_wallet_wallet_proto_depIdxs,
		EnumInfos:         file_pb_wallet_wallet_proto_enumTypes,
		MessageInfos:      file_pb_wallet_wallet_proto_msgTypes,
	}.Build()
	File_pb_wallet_wallet_proto = out.File
	file_pb_wallet_wallet_proto_rawDesc = nil
	file_pb_wallet_wallet_proto_goTypes = nil
	file_pb_wallet_wallet_proto_depIdxs = nil
}
