package service

const (
	ERROR_CODE_AUTH_ACCOUNT_TYPE_ERR        int32 = 31001
	ERROR_CODE_AUTH_ACCOUNT_OR_PASSWORD_ERR int32 = 31002
	ERROR_CODE_AUTH_QUERY_DB_FAILED         int32 = 31003
	ERROR_CODE_AUTH_REDIS_GET_FAILED        int32 = 31004
	ERROR_CODE_AUTH_REGISTER_ERR            int32 = 31005
	ERROR_CODE_AUTH_INSERT_VALUE_FAILED     int32 = 31006
)

const (
	ERROR_AUTH_ACCOUNT_TYPE_ERR        = "登录类型错误"
	ERROR_AUTH_ACCOUNT_OR_PASSWORD_ERR = "账户或密码错误"
	ERROR_AUTH_QUERY_DB_FAILED         = "查询失败"
	ERROR_AUTH_REDIS_GET_FAILED        = "读取redis缓存失败"
	ERROR_AUTH_REGISTER_TYPE_ERR       = "注册失败"
	ERROR_AUTH_INSERT_VALUE_FAILED     = "数据入库失败"
)
