package service

const (
	ERROR_CODE_CHAT_MEMBER_QUERY_DB_FAILED      int32 = 100001
	ERROR_CODE_CHAT_MEMBER_GRPC_SERVICE_FAILURE int32 = 100002 // 服务故障
	ERROR_CODE_CHAT_MEMBER_CHCHE_MEMBER_FAILED  int32 = 100003
	ERROR_CODE_CHAT_MEMBER_MISS_USER_INFO       int32 = 100004
	ERROR_CODE_CHAT_MEMBER_UPDATE_VALUE_FAILED  int32 = 100005
)

const (
	ERROR_CHAT_MEMBER_QUERY_DB_FAILED      = "查询失败"
	ERROR_CHAT_MEMBER_GRPC_SERVICE_FAILURE = "服务故障"
	ERROR_CHAT_MEMBER_CHCHE_MEMBER_FAILED  = "缓存成员信息失败"
	ERROR_CHAT_MEMBER_MISS_USER_INFO       = "缺失用户信息"
	ERROR_CHAT_MEMBER_UPDATE_VALUE_FAILED  = "更新Value失败"
)
