package service

const (
	ERROR_CODE_CHAT_MEMBER_QUERY_DB_FAILED      int32 = 100001
	ERROR_CODE_CHAT_MEMBER_GRPC_SERVICE_FAILURE int32 = 100002 // 服务故障
)

const (
	ERROR_CHAT_MEMBER_QUERY_DB_FAILED      = "查询失败"
	ERROR_CHAT_MEMBER_GRPC_SERVICE_FAILURE = "服务故障"
)
