package service

const (
	ERROR_CODE_REQUEST_PROTOCOL_UNMARSHAL_ERR int32 = 120001
	ERROR_CODE_REQUEST_GRPC_SERVICE_FAILURE   int32 = 120002
	ERROR_CODE_REQUEST_INSERT_VALUE_FAILED    int32 = 120003
	ERROR_CODE_REQUEST_UPDATE_VALUE_FAILED    int32 = 120004
	ERROR_CODE_REQUEST_QUERY_DB_FAILED        int32 = 120005
)

const (
	ERROR_REQUEST_PROTOCOL_UNMARSHAL_ERR = "协议反序列化错误"
	ERROR_REQUEST_GRPC_SERVICE_FAILURE   = "服务故障"
	ERROR_REQUEST_INSERT_VALUE_FAILED    = "数据入库失败"
	ERROR_REQUEST_UPDATE_VALUE_FAILED    = "更新Value失败"
	ERROR_REQUEST_QUERY_DB_FAILED        = "查询失败"
)
