// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: pb_ofps/ofps.proto

package pb_ofps

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// OfflinePushClient is the client API for OfflinePush service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OfflinePushClient interface {
	OfflinePushMessage(ctx context.Context, in *OfflinePushMessageReq, opts ...grpc.CallOption) (*OfflinePushMessageResp, error)
}

type offlinePushClient struct {
	cc grpc.ClientConnInterface
}

func NewOfflinePushClient(cc grpc.ClientConnInterface) OfflinePushClient {
	return &offlinePushClient{cc}
}

func (c *offlinePushClient) OfflinePushMessage(ctx context.Context, in *OfflinePushMessageReq, opts ...grpc.CallOption) (*OfflinePushMessageResp, error) {
	out := new(OfflinePushMessageResp)
	err := c.cc.Invoke(ctx, "/pb_ofps.OfflinePush/OfflinePushMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OfflinePushServer is the server API for OfflinePush service.
// All implementations must embed UnimplementedOfflinePushServer
// for forward compatibility
type OfflinePushServer interface {
	OfflinePushMessage(context.Context, *OfflinePushMessageReq) (*OfflinePushMessageResp, error)
	mustEmbedUnimplementedOfflinePushServer()
}

// UnimplementedOfflinePushServer must be embedded to have forward compatible implementations.
type UnimplementedOfflinePushServer struct {
}

func (UnimplementedOfflinePushServer) OfflinePushMessage(context.Context, *OfflinePushMessageReq) (*OfflinePushMessageResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OfflinePushMessage not implemented")
}
func (UnimplementedOfflinePushServer) mustEmbedUnimplementedOfflinePushServer() {}

// UnsafeOfflinePushServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OfflinePushServer will
// result in compilation errors.
type UnsafeOfflinePushServer interface {
	mustEmbedUnimplementedOfflinePushServer()
}

func RegisterOfflinePushServer(s grpc.ServiceRegistrar, srv OfflinePushServer) {
	s.RegisterService(&OfflinePush_ServiceDesc, srv)
}

func _OfflinePush_OfflinePushMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OfflinePushMessageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OfflinePushServer).OfflinePushMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb_ofps.OfflinePush/OfflinePushMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OfflinePushServer).OfflinePushMessage(ctx, req.(*OfflinePushMessageReq))
	}
	return interceptor(ctx, in, info, handler)
}

// OfflinePush_ServiceDesc is the grpc.ServiceDesc for OfflinePush service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OfflinePush_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb_ofps.OfflinePush",
	HandlerType: (*OfflinePushServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OfflinePushMessage",
			Handler:    _OfflinePush_OfflinePushMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb_ofps/ofps.proto",
}
