// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.5
// source: pb_chat/chat.proto

package pb_chat

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ChatClient is the client API for Chat service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChatClient interface {
	NewGroupChat(ctx context.Context, in *NewGroupChatReq, opts ...grpc.CallOption) (*NewGroupChatResp, error)
	SetGroupChat(ctx context.Context, in *SetGroupChatReq, opts ...grpc.CallOption) (*SetGroupChatResp, error)
}

type chatClient struct {
	cc grpc.ClientConnInterface
}

func NewChatClient(cc grpc.ClientConnInterface) ChatClient {
	return &chatClient{cc}
}

func (c *chatClient) NewGroupChat(ctx context.Context, in *NewGroupChatReq, opts ...grpc.CallOption) (*NewGroupChatResp, error) {
	out := new(NewGroupChatResp)
	err := c.cc.Invoke(ctx, "/pb_chat.Chat/NewGroupChat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) SetGroupChat(ctx context.Context, in *SetGroupChatReq, opts ...grpc.CallOption) (*SetGroupChatResp, error) {
	out := new(SetGroupChatResp)
	err := c.cc.Invoke(ctx, "/pb_chat.Chat/SetGroupChat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatServer is the server API for Chat service.
// All implementations must embed UnimplementedChatServer
// for forward compatibility
type ChatServer interface {
	NewGroupChat(context.Context, *NewGroupChatReq) (*NewGroupChatResp, error)
	SetGroupChat(context.Context, *SetGroupChatReq) (*SetGroupChatResp, error)
	mustEmbedUnimplementedChatServer()
}

// UnimplementedChatServer must be embedded to have forward compatible implementations.
type UnimplementedChatServer struct {
}

func (UnimplementedChatServer) NewGroupChat(context.Context, *NewGroupChatReq) (*NewGroupChatResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewGroupChat not implemented")
}
func (UnimplementedChatServer) SetGroupChat(context.Context, *SetGroupChatReq) (*SetGroupChatResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetGroupChat not implemented")
}
func (UnimplementedChatServer) mustEmbedUnimplementedChatServer() {}

// UnsafeChatServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatServer will
// result in compilation errors.
type UnsafeChatServer interface {
	mustEmbedUnimplementedChatServer()
}

func RegisterChatServer(s grpc.ServiceRegistrar, srv ChatServer) {
	s.RegisterService(&Chat_ServiceDesc, srv)
}

func _Chat_NewGroupChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewGroupChatReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).NewGroupChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb_chat.Chat/NewGroupChat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).NewGroupChat(ctx, req.(*NewGroupChatReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_SetGroupChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetGroupChatReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).SetGroupChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb_chat.Chat/SetGroupChat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).SetGroupChat(ctx, req.(*SetGroupChatReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Chat_ServiceDesc is the grpc.ServiceDesc for Chat service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Chat_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb_chat.Chat",
	HandlerType: (*ChatServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewGroupChat",
			Handler:    _Chat_NewGroupChat_Handler,
		},
		{
			MethodName: "SetGroupChat",
			Handler:    _Chat_SetGroupChat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb_chat/chat.proto",
}
