name: lark_push_server
log: "./configs/logger.yaml"
monitor:
  port: 34001
grpc_server:
  name: lark_push_server
  server_id: 1
  port: 34000
  max_connection_idle: 0
  max_connection_age: 0
  max_connection_age_grace: 0
  time: 7200000
  timeout: 20000
  connection_limit: 2000
  streams_limit: 2000
  max_recv_msg_size: 4096
  credential:
    cert_file: ./configs/tls/grpc/server.pem
    key_file: ./configs/tls/grpc/server.key
    enabled: true
  jaeger:
    host_port: "lark-jaeger:6831"
    sampler_type: "const"
    param: 1
    log_spans: true
    buffer_flush_interval: 1
    max_packet_size: 0
    enabled: true
push_online_server:
  name: lark_online_push_server
  cert:
    cert_file: ./configs/tls/grpc/server.pem
    enabled: true
    server_name_override: lark.com
chat_member_server:
  name: lark_chat_member_server
  cert:
    cert_file: ./configs/tls/grpc/server.pem
    enabled: true
    server_name_override: lark.com
etcd:
  endpoints: ["lark-etcd:12379"]
  schema: lark
  read_timeout: 5000
  write_timeout: 5000
  dial_timeout: 5000
platforms:
 - type: 1
   name: Android
   offline_push: true
 - type: 2
   name: iOS
   offline_push: true
msg_consumer:
  address: ["lark-kafka:9092"]
  topic: ["msg2inbox"]
  group_id: push
redis:
  address: ["lark-redis:63791"]
  db: 0
  password: lark2022
  prefix: "LK:"