// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: pb_chat_member/chat_member.proto

package pb_chat_member

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	pb_enum "lark/pkg/proto/pb_enum"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetChatMemberUidListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChatId int64 `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
}

func (x *GetChatMemberUidListReq) Reset() {
	*x = GetChatMemberUidListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_chat_member_chat_member_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetChatMemberUidListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatMemberUidListReq) ProtoMessage() {}

func (x *GetChatMemberUidListReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_chat_member_chat_member_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatMemberUidListReq.ProtoReflect.Descriptor instead.
func (*GetChatMemberUidListReq) Descriptor() ([]byte, []int) {
	return file_pb_chat_member_chat_member_proto_rawDescGZIP(), []int{0}
}

func (x *GetChatMemberUidListReq) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

type GetChatMemberUidListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string  `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	List []int64 `protobuf:"varint,3,rep,packed,name=list,proto3" json:"list,omitempty"`
}

func (x *GetChatMemberUidListResp) Reset() {
	*x = GetChatMemberUidListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_chat_member_chat_member_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetChatMemberUidListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatMemberUidListResp) ProtoMessage() {}

func (x *GetChatMemberUidListResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_chat_member_chat_member_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatMemberUidListResp.ProtoReflect.Descriptor instead.
func (*GetChatMemberUidListResp) Descriptor() ([]byte, []int) {
	return file_pb_chat_member_chat_member_proto_rawDescGZIP(), []int{1}
}

func (x *GetChatMemberUidListResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetChatMemberUidListResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetChatMemberUidListResp) GetList() []int64 {
	if x != nil {
		return x.List
	}
	return nil
}

type GetChatMemberPushConfigListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChatId int64 `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
}

func (x *GetChatMemberPushConfigListReq) Reset() {
	*x = GetChatMemberPushConfigListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_chat_member_chat_member_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetChatMemberPushConfigListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatMemberPushConfigListReq) ProtoMessage() {}

func (x *GetChatMemberPushConfigListReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_chat_member_chat_member_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatMemberPushConfigListReq.ProtoReflect.Descriptor instead.
func (*GetChatMemberPushConfigListReq) Descriptor() ([]byte, []int) {
	return file_pb_chat_member_chat_member_proto_rawDescGZIP(), []int{2}
}

func (x *GetChatMemberPushConfigListReq) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

type GetChatMemberPushConfigListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32                   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string                  `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	List []*ChatMemberPushConfig `protobuf:"bytes,3,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *GetChatMemberPushConfigListResp) Reset() {
	*x = GetChatMemberPushConfigListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_chat_member_chat_member_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetChatMemberPushConfigListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatMemberPushConfigListResp) ProtoMessage() {}

func (x *GetChatMemberPushConfigListResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_chat_member_chat_member_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatMemberPushConfigListResp.ProtoReflect.Descriptor instead.
func (*GetChatMemberPushConfigListResp) Descriptor() ([]byte, []int) {
	return file_pb_chat_member_chat_member_proto_rawDescGZIP(), []int{3}
}

func (x *GetChatMemberPushConfigListResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetChatMemberPushConfigListResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetChatMemberPushConfigListResp) GetList() []*ChatMemberPushConfig {
	if x != nil {
		return x.List
	}
	return nil
}

type GetChatMemberPushConfigReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChatId int64 `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Uid    int64 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *GetChatMemberPushConfigReq) Reset() {
	*x = GetChatMemberPushConfigReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_chat_member_chat_member_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetChatMemberPushConfigReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatMemberPushConfigReq) ProtoMessage() {}

func (x *GetChatMemberPushConfigReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_chat_member_chat_member_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatMemberPushConfigReq.ProtoReflect.Descriptor instead.
func (*GetChatMemberPushConfigReq) Descriptor() ([]byte, []int) {
	return file_pb_chat_member_chat_member_proto_rawDescGZIP(), []int{4}
}

func (x *GetChatMemberPushConfigReq) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *GetChatMemberPushConfigReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type GetChatMemberPushConfigResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code   int32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg    string                `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Config *ChatMemberPushConfig `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
}

func (x *GetChatMemberPushConfigResp) Reset() {
	*x = GetChatMemberPushConfigResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_chat_member_chat_member_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetChatMemberPushConfigResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatMemberPushConfigResp) ProtoMessage() {}

func (x *GetChatMemberPushConfigResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_chat_member_chat_member_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatMemberPushConfigResp.ProtoReflect.Descriptor instead.
func (*GetChatMemberPushConfigResp) Descriptor() ([]byte, []int) {
	return file_pb_chat_member_chat_member_proto_rawDescGZIP(), []int{5}
}

func (x *GetChatMemberPushConfigResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetChatMemberPushConfigResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetChatMemberPushConfigResp) GetConfig() *ChatMemberPushConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type GetChatMemberSettingReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChatId int64 `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Uid    int64 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *GetChatMemberSettingReq) Reset() {
	*x = GetChatMemberSettingReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_chat_member_chat_member_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetChatMemberSettingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatMemberSettingReq) ProtoMessage() {}

func (x *GetChatMemberSettingReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_chat_member_chat_member_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatMemberSettingReq.ProtoReflect.Descriptor instead.
func (*GetChatMemberSettingReq) Descriptor() ([]byte, []int) {
	return file_pb_chat_member_chat_member_proto_rawDescGZIP(), []int{6}
}

func (x *GetChatMemberSettingReq) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *GetChatMemberSettingReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type GetChatMemberSettingResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg     string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Setting string `protobuf:"bytes,3,opt,name=setting,proto3" json:"setting,omitempty"`
}

func (x *GetChatMemberSettingResp) Reset() {
	*x = GetChatMemberSettingResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_chat_member_chat_member_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetChatMemberSettingResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatMemberSettingResp) ProtoMessage() {}

func (x *GetChatMemberSettingResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_chat_member_chat_member_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatMemberSettingResp.ProtoReflect.Descriptor instead.
func (*GetChatMemberSettingResp) Descriptor() ([]byte, []int) {
	return file_pb_chat_member_chat_member_proto_rawDescGZIP(), []int{7}
}

func (x *GetChatMemberSettingResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetChatMemberSettingResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetChatMemberSettingResp) GetSetting() string {
	if x != nil {
		return x.Setting
	}
	return ""
}

type GetChatMemberInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChatId int64 `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Uid    int64 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *GetChatMemberInfoReq) Reset() {
	*x = GetChatMemberInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_chat_member_chat_member_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetChatMemberInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatMemberInfoReq) ProtoMessage() {}

func (x *GetChatMemberInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_chat_member_chat_member_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatMemberInfoReq.ProtoReflect.Descriptor instead.
func (*GetChatMemberInfoReq) Descriptor() ([]byte, []int) {
	return file_pb_chat_member_chat_member_proto_rawDescGZIP(), []int{8}
}

func (x *GetChatMemberInfoReq) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *GetChatMemberInfoReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type GetChatMemberInfoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32           `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string          `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Info *ChatMemberInfo `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *GetChatMemberInfoResp) Reset() {
	*x = GetChatMemberInfoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_chat_member_chat_member_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetChatMemberInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatMemberInfoResp) ProtoMessage() {}

func (x *GetChatMemberInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_chat_member_chat_member_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatMemberInfoResp.ProtoReflect.Descriptor instead.
func (*GetChatMemberInfoResp) Descriptor() ([]byte, []int) {
	return file_pb_chat_member_chat_member_proto_rawDescGZIP(), []int{9}
}

func (x *GetChatMemberInfoResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetChatMemberInfoResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetChatMemberInfoResp) GetInfo() *ChatMemberInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type ChatMemberInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChatId      int64             `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	ChatType    pb_enum.CHAT_TYPE `protobuf:"varint,2,opt,name=chat_type,json=chatType,proto3,enum=pb_enum.CHAT_TYPE" json:"chat_type,omitempty"`
	Uid         int64             `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	DisplayName string            `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	AvatarUrl   string            `protobuf:"bytes,5,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
}

func (x *ChatMemberInfo) Reset() {
	*x = ChatMemberInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_chat_member_chat_member_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatMemberInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMemberInfo) ProtoMessage() {}

func (x *ChatMemberInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pb_chat_member_chat_member_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMemberInfo.ProtoReflect.Descriptor instead.
func (*ChatMemberInfo) Descriptor() ([]byte, []int) {
	return file_pb_chat_member_chat_member_proto_rawDescGZIP(), []int{10}
}

func (x *ChatMemberInfo) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *ChatMemberInfo) GetChatType() pb_enum.CHAT_TYPE {
	if x != nil {
		return x.ChatType
	}
	return pb_enum.CHAT_TYPE(0)
}

func (x *ChatMemberInfo) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ChatMemberInfo) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ChatMemberInfo) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

type ChatMemberVerifyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChatId   int64             `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	ChatType pb_enum.CHAT_TYPE `protobuf:"varint,2,opt,name=chat_type,json=chatType,proto3,enum=pb_enum.CHAT_TYPE" json:"chat_type,omitempty"`
	UidList  []int64           `protobuf:"varint,3,rep,packed,name=uid_list,json=uidList,proto3" json:"uid_list,omitempty"`
}

func (x *ChatMemberVerifyReq) Reset() {
	*x = ChatMemberVerifyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_chat_member_chat_member_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatMemberVerifyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMemberVerifyReq) ProtoMessage() {}

func (x *ChatMemberVerifyReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_chat_member_chat_member_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMemberVerifyReq.ProtoReflect.Descriptor instead.
func (*ChatMemberVerifyReq) Descriptor() ([]byte, []int) {
	return file_pb_chat_member_chat_member_proto_rawDescGZIP(), []int{11}
}

func (x *ChatMemberVerifyReq) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *ChatMemberVerifyReq) GetChatType() pb_enum.CHAT_TYPE {
	if x != nil {
		return x.ChatType
	}
	return pb_enum.CHAT_TYPE(0)
}

func (x *ChatMemberVerifyReq) GetUidList() []int64 {
	if x != nil {
		return x.UidList
	}
	return nil
}

type ChatMemberVerifyResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Ok   bool   `protobuf:"varint,3,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *ChatMemberVerifyResp) Reset() {
	*x = ChatMemberVerifyResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_chat_member_chat_member_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatMemberVerifyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMemberVerifyResp) ProtoMessage() {}

func (x *ChatMemberVerifyResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_chat_member_chat_member_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMemberVerifyResp.ProtoReflect.Descriptor instead.
func (*ChatMemberVerifyResp) Descriptor() ([]byte, []int) {
	return file_pb_chat_member_chat_member_proto_rawDescGZIP(), []int{12}
}

func (x *ChatMemberVerifyResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ChatMemberVerifyResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ChatMemberVerifyResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type ChatSetting struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerId  int32   `protobuf:"varint,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Platforms []int32 `protobuf:"varint,2,rep,packed,name=platforms,proto3" json:"platforms,omitempty"`
}

func (x *ChatSetting) Reset() {
	*x = ChatSetting{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_chat_member_chat_member_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatSetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatSetting) ProtoMessage() {}

func (x *ChatSetting) ProtoReflect() protoreflect.Message {
	mi := &file_pb_chat_member_chat_member_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatSetting.ProtoReflect.Descriptor instead.
func (*ChatSetting) Descriptor() ([]byte, []int) {
	return file_pb_chat_member_chat_member_proto_rawDescGZIP(), []int{13}
}

func (x *ChatSetting) GetServerId() int32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *ChatSetting) GetPlatforms() []int32 {
	if x != nil {
		return x.Platforms
	}
	return nil
}

type ChatMemberOnlineReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid      int64                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	ServerId int32                 `protobuf:"varint,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`            // 分配的ws服务器
	Platform pb_enum.PLATFORM_TYPE `protobuf:"varint,3,opt,name=platform,proto3,enum=pb_enum.PLATFORM_TYPE" json:"platform,omitempty"` // 上线终端平台
}

func (x *ChatMemberOnlineReq) Reset() {
	*x = ChatMemberOnlineReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_chat_member_chat_member_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatMemberOnlineReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMemberOnlineReq) ProtoMessage() {}

func (x *ChatMemberOnlineReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_chat_member_chat_member_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMemberOnlineReq.ProtoReflect.Descriptor instead.
func (*ChatMemberOnlineReq) Descriptor() ([]byte, []int) {
	return file_pb_chat_member_chat_member_proto_rawDescGZIP(), []int{14}
}

func (x *ChatMemberOnlineReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ChatMemberOnlineReq) GetServerId() int32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *ChatMemberOnlineReq) GetPlatform() pb_enum.PLATFORM_TYPE {
	if x != nil {
		return x.Platform
	}
	return pb_enum.PLATFORM_TYPE(0)
}

type ChatMemberOnlineResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *ChatMemberOnlineResp) Reset() {
	*x = ChatMemberOnlineResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_chat_member_chat_member_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatMemberOnlineResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMemberOnlineResp) ProtoMessage() {}

func (x *ChatMemberOnlineResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_chat_member_chat_member_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMemberOnlineResp.ProtoReflect.Descriptor instead.
func (*ChatMemberOnlineResp) Descriptor() ([]byte, []int) {
	return file_pb_chat_member_chat_member_proto_rawDescGZIP(), []int{15}
}

func (x *ChatMemberOnlineResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ChatMemberOnlineResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type ChatMemberPushConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChatId   int64                 `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Uid      int64                 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Mute     pb_enum.MUTE_TYPE     `protobuf:"varint,3,opt,name=mute,proto3,enum=pb_enum.MUTE_TYPE" json:"mute,omitempty"`
	Platform pb_enum.PLATFORM_TYPE `protobuf:"varint,4,opt,name=platform,proto3,enum=pb_enum.PLATFORM_TYPE" json:"platform,omitempty"`
	ServerId int32                 `protobuf:"varint,5,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
}

func (x *ChatMemberPushConfig) Reset() {
	*x = ChatMemberPushConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_chat_member_chat_member_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatMemberPushConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMemberPushConfig) ProtoMessage() {}

func (x *ChatMemberPushConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pb_chat_member_chat_member_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMemberPushConfig.ProtoReflect.Descriptor instead.
func (*ChatMemberPushConfig) Descriptor() ([]byte, []int) {
	return file_pb_chat_member_chat_member_proto_rawDescGZIP(), []int{16}
}

func (x *ChatMemberPushConfig) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *ChatMemberPushConfig) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ChatMemberPushConfig) GetMute() pb_enum.MUTE_TYPE {
	if x != nil {
		return x.Mute
	}
	return pb_enum.MUTE_TYPE(0)
}

func (x *ChatMemberPushConfig) GetPlatform() pb_enum.PLATFORM_TYPE {
	if x != nil {
		return x.Platform
	}
	return pb_enum.PLATFORM_TYPE(0)
}

func (x *ChatMemberPushConfig) GetServerId() int32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

var File_pb_chat_member_chat_member_proto protoreflect.FileDescriptor

var file_pb_chat_member_chat_member_proto_rawDesc = []byte{
	0x0a, 0x20, 0x70, 0x62, 0x5f, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x2f, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0e, 0x70, 0x62, 0x5f, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x6d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x1a, 0x12, 0x70, 0x62, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x2f, 0x65, 0x6e, 0x75, 0x6d,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x32, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61,
	0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x55, 0x69, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x63, 0x68, 0x61, 0x74, 0x49, 0x64, 0x22, 0x54, 0x0a, 0x18, 0x47, 0x65,
	0x74, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x55, 0x69, 0x64, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73,
	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x12, 0x0a, 0x04,
	0x6c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x03, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74,
	0x22, 0x39, 0x0a, 0x1e, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x50, 0x75, 0x73, 0x68, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x63, 0x68, 0x61, 0x74, 0x49, 0x64, 0x22, 0x81, 0x01, 0x0a, 0x1f,
	0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x50, 0x75, 0x73,
	0x68, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x38, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x70, 0x62, 0x5f, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x6d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x50,
	0x75, 0x73, 0x68, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22,
	0x47, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x50, 0x75, 0x73, 0x68, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a,
	0x07, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x63, 0x68, 0x61, 0x74, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x81, 0x01, 0x0a, 0x1b, 0x47, 0x65, 0x74,
	0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x50, 0x75, 0x73, 0x68, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x3c,
	0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24,
	0x2e, 0x70, 0x62, 0x5f, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e,
	0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x50, 0x75, 0x73, 0x68, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x44, 0x0a, 0x17,
	0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x53, 0x65, 0x74,
	0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x74, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x63, 0x68, 0x61, 0x74, 0x49, 0x64,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75,
	0x69, 0x64, 0x22, 0x5a, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12,
	0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6d, 0x73, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x22, 0x41,
	0x0a, 0x14, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x63, 0x68, 0x61, 0x74, 0x49, 0x64, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69,
	0x64, 0x22, 0x71, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67,
	0x12, 0x32, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e,
	0x2e, 0x70, 0x62, 0x5f, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e,
	0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04,
	0x69, 0x6e, 0x66, 0x6f, 0x22, 0xae, 0x01, 0x0a, 0x0e, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x74, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x63, 0x68, 0x61, 0x74, 0x49, 0x64,
	0x12, 0x2f, 0x0a, 0x09, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x43, 0x48,
	0x41, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x52, 0x08, 0x63, 0x68, 0x61, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03,
	0x75, 0x69, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c,
	0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72,
	0x5f, 0x75, 0x72, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x76, 0x61, 0x74,
	0x61, 0x72, 0x55, 0x72, 0x6c, 0x22, 0x7a, 0x0a, 0x13, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07,
	0x63, 0x68, 0x61, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x63,
	0x68, 0x61, 0x74, 0x49, 0x64, 0x12, 0x2f, 0x0a, 0x09, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x5f, 0x65, 0x6e,
	0x75, 0x6d, 0x2e, 0x43, 0x48, 0x41, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x52, 0x08, 0x63, 0x68,
	0x61, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x75, 0x69, 0x64, 0x5f, 0x6c, 0x69,
	0x73, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x03, 0x52, 0x07, 0x75, 0x69, 0x64, 0x4c, 0x69, 0x73,
	0x74, 0x22, 0x4c, 0x0a, 0x14, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x56,
	0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12,
	0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x22,
	0x48, 0x0a, 0x0b, 0x43, 0x68, 0x61, 0x74, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x1b,
	0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x70,
	0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x09,
	0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x73, 0x22, 0x78, 0x0a, 0x13, 0x43, 0x68, 0x61,
	0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75,
	0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x32, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x16, 0x2e, 0x70, 0x62, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x50, 0x4c, 0x41, 0x54,
	0x46, 0x4f, 0x52, 0x4d, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66,
	0x6f, 0x72, 0x6d, 0x22, 0x3c, 0x0a, 0x14, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73,
	0x67, 0x22, 0xba, 0x01, 0x0a, 0x14, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x50, 0x75, 0x73, 0x68, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x68,
	0x61, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x63, 0x68, 0x61,
	0x74, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x26, 0x0a, 0x04, 0x6d, 0x75, 0x74, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x4d, 0x55,
	0x54, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x52, 0x04, 0x6d, 0x75, 0x74, 0x65, 0x12, 0x32, 0x0a,
	0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x16, 0x2e, 0x70, 0x62, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x50, 0x4c, 0x41, 0x54, 0x46, 0x4f,
	0x52, 0x4d, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72,
	0x6d, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x32, 0xf6,
	0x05, 0x0a, 0x0a, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x69, 0x0a,
	0x14, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x55, 0x69,
	0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x27, 0x2e, 0x70, 0x62, 0x5f, 0x63, 0x68, 0x61, 0x74, 0x5f,
	0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x55, 0x69, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x28,
	0x2e, 0x70, 0x62, 0x5f, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e,
	0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x55, 0x69, 0x64,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x72, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x43,
	0x68, 0x61, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x50, 0x75, 0x73, 0x68, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x12, 0x2a, 0x2e, 0x70, 0x62, 0x5f, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x6d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x50, 0x75, 0x73, 0x68, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x1a,
	0x2b, 0x2e, 0x70, 0x62, 0x5f, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x2e, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x50, 0x75,
	0x73, 0x68, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70, 0x12, 0x7e, 0x0a, 0x1b,
	0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x50, 0x75, 0x73,
	0x68, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2e, 0x2e, 0x70, 0x62,
	0x5f, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74,
	0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x50, 0x75, 0x73, 0x68, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x2f, 0x2e, 0x70, 0x62,
	0x5f, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74,
	0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x50, 0x75, 0x73, 0x68, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x69, 0x0a, 0x14,
	0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x53, 0x65, 0x74,
	0x74, 0x69, 0x6e, 0x67, 0x12, 0x27, 0x2e, 0x70, 0x62, 0x5f, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x6d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x28, 0x2e,
	0x70, 0x62, 0x5f, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x47,
	0x65, 0x74, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x53, 0x65, 0x74, 0x74,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x12, 0x60, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x43, 0x68,
	0x61, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x24, 0x2e, 0x70,
	0x62, 0x5f, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x47, 0x65,
	0x74, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x71, 0x1a, 0x25, 0x2e, 0x70, 0x62, 0x5f, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x6d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x5d, 0x0a, 0x10, 0x43, 0x68, 0x61,
	0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x12, 0x23, 0x2e,
	0x70, 0x62, 0x5f, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x43,
	0x68, 0x61, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52,
	0x65, 0x71, 0x1a, 0x24, 0x2e, 0x70, 0x62, 0x5f, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x6d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x56, 0x65,
	0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x5d, 0x0a, 0x10, 0x43, 0x68, 0x61, 0x74,
	0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x23, 0x2e, 0x70,
	0x62, 0x5f, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x43, 0x68,
	0x61, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65,
	0x71, 0x1a, 0x24, 0x2e, 0x70, 0x62, 0x5f, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x6d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x4f, 0x6e, 0x6c,
	0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x42, 0x21, 0x5a, 0x1f, 0x2e, 0x2f, 0x70, 0x62, 0x5f,
	0x63, 0x68, 0x61, 0x74, 0x5f, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x3b, 0x70, 0x62, 0x5f, 0x63,
	0x68, 0x61, 0x74, 0x5f, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_pb_chat_member_chat_member_proto_rawDescOnce sync.Once
	file_pb_chat_member_chat_member_proto_rawDescData = file_pb_chat_member_chat_member_proto_rawDesc
)

func file_pb_chat_member_chat_member_proto_rawDescGZIP() []byte {
	file_pb_chat_member_chat_member_proto_rawDescOnce.Do(func() {
		file_pb_chat_member_chat_member_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_chat_member_chat_member_proto_rawDescData)
	})
	return file_pb_chat_member_chat_member_proto_rawDescData
}

var file_pb_chat_member_chat_member_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_pb_chat_member_chat_member_proto_goTypes = []interface{}{
	(*GetChatMemberUidListReq)(nil),         // 0: pb_chat_member.GetChatMemberUidListReq
	(*GetChatMemberUidListResp)(nil),        // 1: pb_chat_member.GetChatMemberUidListResp
	(*GetChatMemberPushConfigListReq)(nil),  // 2: pb_chat_member.GetChatMemberPushConfigListReq
	(*GetChatMemberPushConfigListResp)(nil), // 3: pb_chat_member.GetChatMemberPushConfigListResp
	(*GetChatMemberPushConfigReq)(nil),      // 4: pb_chat_member.GetChatMemberPushConfigReq
	(*GetChatMemberPushConfigResp)(nil),     // 5: pb_chat_member.GetChatMemberPushConfigResp
	(*GetChatMemberSettingReq)(nil),         // 6: pb_chat_member.GetChatMemberSettingReq
	(*GetChatMemberSettingResp)(nil),        // 7: pb_chat_member.GetChatMemberSettingResp
	(*GetChatMemberInfoReq)(nil),            // 8: pb_chat_member.GetChatMemberInfoReq
	(*GetChatMemberInfoResp)(nil),           // 9: pb_chat_member.GetChatMemberInfoResp
	(*ChatMemberInfo)(nil),                  // 10: pb_chat_member.ChatMemberInfo
	(*ChatMemberVerifyReq)(nil),             // 11: pb_chat_member.ChatMemberVerifyReq
	(*ChatMemberVerifyResp)(nil),            // 12: pb_chat_member.ChatMemberVerifyResp
	(*ChatSetting)(nil),                     // 13: pb_chat_member.ChatSetting
	(*ChatMemberOnlineReq)(nil),             // 14: pb_chat_member.ChatMemberOnlineReq
	(*ChatMemberOnlineResp)(nil),            // 15: pb_chat_member.ChatMemberOnlineResp
	(*ChatMemberPushConfig)(nil),            // 16: pb_chat_member.ChatMemberPushConfig
	(pb_enum.CHAT_TYPE)(0),                  // 17: pb_enum.CHAT_TYPE
	(pb_enum.PLATFORM_TYPE)(0),              // 18: pb_enum.PLATFORM_TYPE
	(pb_enum.MUTE_TYPE)(0),                  // 19: pb_enum.MUTE_TYPE
}
var file_pb_chat_member_chat_member_proto_depIdxs = []int32{
	16, // 0: pb_chat_member.GetChatMemberPushConfigListResp.list:type_name -> pb_chat_member.ChatMemberPushConfig
	16, // 1: pb_chat_member.GetChatMemberPushConfigResp.config:type_name -> pb_chat_member.ChatMemberPushConfig
	10, // 2: pb_chat_member.GetChatMemberInfoResp.info:type_name -> pb_chat_member.ChatMemberInfo
	17, // 3: pb_chat_member.ChatMemberInfo.chat_type:type_name -> pb_enum.CHAT_TYPE
	17, // 4: pb_chat_member.ChatMemberVerifyReq.chat_type:type_name -> pb_enum.CHAT_TYPE
	18, // 5: pb_chat_member.ChatMemberOnlineReq.platform:type_name -> pb_enum.PLATFORM_TYPE
	19, // 6: pb_chat_member.ChatMemberPushConfig.mute:type_name -> pb_enum.MUTE_TYPE
	18, // 7: pb_chat_member.ChatMemberPushConfig.platform:type_name -> pb_enum.PLATFORM_TYPE
	0,  // 8: pb_chat_member.ChatMember.GetChatMemberUidList:input_type -> pb_chat_member.GetChatMemberUidListReq
	4,  // 9: pb_chat_member.ChatMember.GetChatMemberPushConfig:input_type -> pb_chat_member.GetChatMemberPushConfigReq
	2,  // 10: pb_chat_member.ChatMember.GetChatMemberPushConfigList:input_type -> pb_chat_member.GetChatMemberPushConfigListReq
	6,  // 11: pb_chat_member.ChatMember.GetChatMemberSetting:input_type -> pb_chat_member.GetChatMemberSettingReq
	8,  // 12: pb_chat_member.ChatMember.GetChatMemberInfo:input_type -> pb_chat_member.GetChatMemberInfoReq
	11, // 13: pb_chat_member.ChatMember.ChatMemberVerify:input_type -> pb_chat_member.ChatMemberVerifyReq
	14, // 14: pb_chat_member.ChatMember.ChatMemberOnline:input_type -> pb_chat_member.ChatMemberOnlineReq
	1,  // 15: pb_chat_member.ChatMember.GetChatMemberUidList:output_type -> pb_chat_member.GetChatMemberUidListResp
	5,  // 16: pb_chat_member.ChatMember.GetChatMemberPushConfig:output_type -> pb_chat_member.GetChatMemberPushConfigResp
	3,  // 17: pb_chat_member.ChatMember.GetChatMemberPushConfigList:output_type -> pb_chat_member.GetChatMemberPushConfigListResp
	7,  // 18: pb_chat_member.ChatMember.GetChatMemberSetting:output_type -> pb_chat_member.GetChatMemberSettingResp
	9,  // 19: pb_chat_member.ChatMember.GetChatMemberInfo:output_type -> pb_chat_member.GetChatMemberInfoResp
	12, // 20: pb_chat_member.ChatMember.ChatMemberVerify:output_type -> pb_chat_member.ChatMemberVerifyResp
	15, // 21: pb_chat_member.ChatMember.ChatMemberOnline:output_type -> pb_chat_member.ChatMemberOnlineResp
	15, // [15:22] is the sub-list for method output_type
	8,  // [8:15] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_pb_chat_member_chat_member_proto_init() }
func file_pb_chat_member_chat_member_proto_init() {
	if File_pb_chat_member_chat_member_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_chat_member_chat_member_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetChatMemberUidListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_chat_member_chat_member_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetChatMemberUidListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_chat_member_chat_member_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetChatMemberPushConfigListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_chat_member_chat_member_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetChatMemberPushConfigListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_chat_member_chat_member_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetChatMemberPushConfigReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_chat_member_chat_member_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetChatMemberPushConfigResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_chat_member_chat_member_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetChatMemberSettingReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_chat_member_chat_member_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetChatMemberSettingResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_chat_member_chat_member_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetChatMemberInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_chat_member_chat_member_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetChatMemberInfoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_chat_member_chat_member_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatMemberInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_chat_member_chat_member_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatMemberVerifyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_chat_member_chat_member_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatMemberVerifyResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_chat_member_chat_member_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatSetting); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_chat_member_chat_member_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatMemberOnlineReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_chat_member_chat_member_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatMemberOnlineResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_chat_member_chat_member_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatMemberPushConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_chat_member_chat_member_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_chat_member_chat_member_proto_goTypes,
		DependencyIndexes: file_pb_chat_member_chat_member_proto_depIdxs,
		MessageInfos:      file_pb_chat_member_chat_member_proto_msgTypes,
	}.Build()
	File_pb_chat_member_chat_member_proto = out.File
	file_pb_chat_member_chat_member_proto_rawDesc = nil
	file_pb_chat_member_chat_member_proto_goTypes = nil
	file_pb_chat_member_chat_member_proto_depIdxs = nil
}
