// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: pb_link/link.proto

package pb_link

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	pb_enum "lark/pkg/proto/pb_enum"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserOnlineReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid      int64                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Platform pb_enum.PLATFORM_TYPE `protobuf:"varint,2,opt,name=platform,proto3,enum=pb_enum.PLATFORM_TYPE" json:"platform,omitempty"`
	ServerId int32                 `protobuf:"varint,3,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
}

func (x *UserOnlineReq) Reset() {
	*x = UserOnlineReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_link_link_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserOnlineReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOnlineReq) ProtoMessage() {}

func (x *UserOnlineReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_link_link_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOnlineReq.ProtoReflect.Descriptor instead.
func (*UserOnlineReq) Descriptor() ([]byte, []int) {
	return file_pb_link_link_proto_rawDescGZIP(), []int{0}
}

func (x *UserOnlineReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *UserOnlineReq) GetPlatform() pb_enum.PLATFORM_TYPE {
	if x != nil {
		return x.Platform
	}
	return pb_enum.PLATFORM_TYPE(0)
}

func (x *UserOnlineReq) GetServerId() int32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

type UserOnlineResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *UserOnlineResp) Reset() {
	*x = UserOnlineResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_link_link_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserOnlineResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOnlineResp) ProtoMessage() {}

func (x *UserOnlineResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_link_link_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOnlineResp.ProtoReflect.Descriptor instead.
func (*UserOnlineResp) Descriptor() ([]byte, []int) {
	return file_pb_link_link_proto_rawDescGZIP(), []int{1}
}

func (x *UserOnlineResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UserOnlineResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type UserOfflineReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid      int64                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Platform pb_enum.PLATFORM_TYPE `protobuf:"varint,2,opt,name=platform,proto3,enum=pb_enum.PLATFORM_TYPE" json:"platform,omitempty"`
}

func (x *UserOfflineReq) Reset() {
	*x = UserOfflineReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_link_link_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserOfflineReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOfflineReq) ProtoMessage() {}

func (x *UserOfflineReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_link_link_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOfflineReq.ProtoReflect.Descriptor instead.
func (*UserOfflineReq) Descriptor() ([]byte, []int) {
	return file_pb_link_link_proto_rawDescGZIP(), []int{2}
}

func (x *UserOfflineReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *UserOfflineReq) GetPlatform() pb_enum.PLATFORM_TYPE {
	if x != nil {
		return x.Platform
	}
	return pb_enum.PLATFORM_TYPE(0)
}

type UserOfflineResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *UserOfflineResp) Reset() {
	*x = UserOfflineResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_link_link_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserOfflineResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOfflineResp) ProtoMessage() {}

func (x *UserOfflineResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_link_link_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOfflineResp.ProtoReflect.Descriptor instead.
func (*UserOfflineResp) Descriptor() ([]byte, []int) {
	return file_pb_link_link_proto_rawDescGZIP(), []int{3}
}

func (x *UserOfflineResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UserOfflineResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_pb_link_link_proto protoreflect.FileDescriptor

var file_pb_link_link_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x62, 0x5f, 0x6c, 0x69, 0x6e, 0x6b, 0x2f, 0x6c, 0x69, 0x6e, 0x6b, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x70, 0x62, 0x5f, 0x6c, 0x69, 0x6e, 0x6b, 0x1a, 0x12, 0x70,
	0x62, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x72, 0x0a, 0x0d, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x52,
	0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x03, 0x75, 0x69, 0x64, 0x12, 0x32, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x70, 0x62, 0x5f, 0x65, 0x6e, 0x75, 0x6d,
	0x2e, 0x50, 0x4c, 0x41, 0x54, 0x46, 0x4f, 0x52, 0x4d, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x52, 0x08,
	0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x49, 0x64, 0x22, 0x36, 0x0a, 0x0e, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x6e, 0x6c,
	0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d,
	0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x56, 0x0a,
	0x0e, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69,
	0x64, 0x12, 0x32, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x70, 0x62, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x50, 0x4c,
	0x41, 0x54, 0x46, 0x4f, 0x52, 0x4d, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x52, 0x08, 0x70, 0x6c, 0x61,
	0x74, 0x66, 0x6f, 0x72, 0x6d, 0x22, 0x37, 0x0a, 0x0f, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x66, 0x66,
	0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x32, 0x87,
	0x01, 0x0a, 0x04, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x3d, 0x0a, 0x0a, 0x55, 0x73, 0x65, 0x72, 0x4f,
	0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x16, 0x2e, 0x70, 0x62, 0x5f, 0x6c, 0x69, 0x6e, 0x6b, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e,
	0x70, 0x62, 0x5f, 0x6c, 0x69, 0x6e, 0x6b, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x6e, 0x6c, 0x69,
	0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x40, 0x0a, 0x0b, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x66,
	0x66, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x17, 0x2e, 0x70, 0x62, 0x5f, 0x6c, 0x69, 0x6e, 0x6b, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x18,
	0x2e, 0x70, 0x62, 0x5f, 0x6c, 0x69, 0x6e, 0x6b, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x66, 0x66,
	0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x42, 0x13, 0x5a, 0x11, 0x2e, 0x2f, 0x70, 0x62,
	0x5f, 0x6c, 0x69, 0x6e, 0x6b, 0x3b, 0x70, 0x62, 0x5f, 0x6c, 0x69, 0x6e, 0x6b, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_link_link_proto_rawDescOnce sync.Once
	file_pb_link_link_proto_rawDescData = file_pb_link_link_proto_rawDesc
)

func file_pb_link_link_proto_rawDescGZIP() []byte {
	file_pb_link_link_proto_rawDescOnce.Do(func() {
		file_pb_link_link_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_link_link_proto_rawDescData)
	})
	return file_pb_link_link_proto_rawDescData
}

var file_pb_link_link_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pb_link_link_proto_goTypes = []interface{}{
	(*UserOnlineReq)(nil),      // 0: pb_link.UserOnlineReq
	(*UserOnlineResp)(nil),     // 1: pb_link.UserOnlineResp
	(*UserOfflineReq)(nil),     // 2: pb_link.UserOfflineReq
	(*UserOfflineResp)(nil),    // 3: pb_link.UserOfflineResp
	(pb_enum.PLATFORM_TYPE)(0), // 4: pb_enum.PLATFORM_TYPE
}
var file_pb_link_link_proto_depIdxs = []int32{
	4, // 0: pb_link.UserOnlineReq.platform:type_name -> pb_enum.PLATFORM_TYPE
	4, // 1: pb_link.UserOfflineReq.platform:type_name -> pb_enum.PLATFORM_TYPE
	0, // 2: pb_link.Link.UserOnline:input_type -> pb_link.UserOnlineReq
	2, // 3: pb_link.Link.UserOffline:input_type -> pb_link.UserOfflineReq
	1, // 4: pb_link.Link.UserOnline:output_type -> pb_link.UserOnlineResp
	3, // 5: pb_link.Link.UserOffline:output_type -> pb_link.UserOfflineResp
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pb_link_link_proto_init() }
func file_pb_link_link_proto_init() {
	if File_pb_link_link_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_link_link_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserOnlineReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_link_link_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserOnlineResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_link_link_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserOfflineReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_link_link_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserOfflineResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_link_link_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_link_link_proto_goTypes,
		DependencyIndexes: file_pb_link_link_proto_depIdxs,
		MessageInfos:      file_pb_link_link_proto_msgTypes,
	}.Build()
	File_pb_link_link_proto = out.File
	file_pb_link_link_proto_rawDesc = nil
	file_pb_link_link_proto_goTypes = nil
	file_pb_link_link_proto_depIdxs = nil
}
