package xhttp

const (
	ERROR_CODE_HTTP_REQ_DESERIALIZE_FAILED       int32 = 10001 // 请求参数序列化错误
	ERROR_CODE_HTTP_REQ_PARAM_ERR                int32 = 10002 // 请求参数错误
	ERROR_CODE_HTTP_REQ_NOT_AUTHORIZED           int32 = 10003 // 没有授权
	ERROR_CODE_HTTP_REGISTER_FAILED              int32 = 10004 // 注册失败
	ERROR_CODE_HTTP_TOKEN_FAILED                 int32 = 10005 // 获取TOKEN失败
	ERROR_CODE_HTTP_JWT_TOKEN_ERR                int32 = 10006 // TOKEN 错误
	ERROR_CODE_HTTP_USER_ID_DOESNOT_EXIST        int32 = 10007 // 用户ID信息缺失
	ERROR_CODE_HTTP_JWT_TOKEN_UUID_DOESNOT_EXIST int32 = 10008 // Token 信息缺失
	ERROR_CODE_HTTP_TOKEN_EXPIRED                int32 = 10009 // Token 失效
	ERROR_CODE_HTTP_PLATFORM_DOESNOT_EXIST       int32 = 10010 // 平台信息缺失
	ERROR_CODE_HTTP_GET_USER_INFO_FAILED         int32 = 10011 // 获取用户信息失败
	ERROR_CODE_HTTP_ADD_FRIEND_FAILED            int32 = 10012 // 添加好友失败
	ERROR_CODE_HTTP_SERVICE_FAILURE              int32 = 10013 // 服务故障
	ERROR_CODE_HTTP_MESSAGE_ENQUEUE_FAILED       int32 = 10014 // 消息入队失败
	ERROR_CODE_HTTP_PRESIGNED_FAILED             int32 = 10015 // 上传文件预先签署失败
	ERROR_CODE_HTTP_READ_UPLOAD_FILE_FAILED      int32 = 10016 // 读取上传文件失败
	ERROR_CODE_HTTP_OPEN_UPLOAD_FILE_FAILED      int32 = 10017 // 打开上传文件失败
	ERROR_CODE_HTTP_CROP_PHOTO_FAILED            int32 = 10018 // 裁剪图片失败
)

const (
	ERROR_CODE_HTTP_400 = 400
)
