package service

const (
	ERROR_CODE_WS_PROTOCOL_UNMARSHAL_ERR int32 = 61001
	ERROR_CODE_WS_PROTOCOL_MARSHAL_ERR   int32 = 61002
	ERROR_CODE_WS_TOPIC_ID_ERR           int32 = 61003
	ERROR_CODE_WS_GRPC_SERVICE_FAILURE   int32 = 61004
	ERROR_CODE_WS_ASSEMBLY_PROTOCOL_ERR  int32 = 61005
)

const (
	ERROR_WS_PROTOCOL_UNMARSHAL_ERR = "协议反序列化错误"
	ERROR_WS_PROTOCOL_MARSHAL_ERR   = "协议列化错误"
	ERROR_WS_TOPIC_ID_ERR           = "消息主题错误"
	ERROR_WS_GRPC_SERVICE_FAILURE   = "服务故障"
	ERROR_WS_ASSEMBLY_PROTOCOL_ERR  = "组装协议错误"
)
