// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: pb_enum/enum.proto

package pb_enum

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ACCOUNT_TYPE int32

const (
	ACCOUNT_TYPE_UNKNOWN_ACCOUNT_TYPE ACCOUNT_TYPE = 0
	ACCOUNT_TYPE_MOBILE               ACCOUNT_TYPE = 1 // 手机登录
	ACCOUNT_TYPE_LARK                 ACCOUNT_TYPE = 2 // lark账户登录
)

// Enum value maps for ACCOUNT_TYPE.
var (
	ACCOUNT_TYPE_name = map[int32]string{
		0: "UNKNOWN_ACCOUNT_TYPE",
		1: "MOBILE",
		2: "LARK",
	}
	ACCOUNT_TYPE_value = map[string]int32{
		"UNKNOWN_ACCOUNT_TYPE": 0,
		"MOBILE":               1,
		"LARK":                 2,
	}
)

func (x ACCOUNT_TYPE) Enum() *ACCOUNT_TYPE {
	p := new(ACCOUNT_TYPE)
	*p = x
	return p
}

func (x ACCOUNT_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ACCOUNT_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_enum_enum_proto_enumTypes[0].Descriptor()
}

func (ACCOUNT_TYPE) Type() protoreflect.EnumType {
	return &file_pb_enum_enum_proto_enumTypes[0]
}

func (x ACCOUNT_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ACCOUNT_TYPE.Descriptor instead.
func (ACCOUNT_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_pb_enum_enum_proto_rawDescGZIP(), []int{0}
}

type TOPIC int32

const (
	TOPIC_UNKNOWN_TOPIC TOPIC = 0
	TOPIC_CHAT          TOPIC = 1 // 聊天
)

// Enum value maps for TOPIC.
var (
	TOPIC_name = map[int32]string{
		0: "UNKNOWN_TOPIC",
		1: "CHAT",
	}
	TOPIC_value = map[string]int32{
		"UNKNOWN_TOPIC": 0,
		"CHAT":          1,
	}
)

func (x TOPIC) Enum() *TOPIC {
	p := new(TOPIC)
	*p = x
	return p
}

func (x TOPIC) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TOPIC) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_enum_enum_proto_enumTypes[1].Descriptor()
}

func (TOPIC) Type() protoreflect.EnumType {
	return &file_pb_enum_enum_proto_enumTypes[1]
}

func (x TOPIC) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TOPIC.Descriptor instead.
func (TOPIC) EnumDescriptor() ([]byte, []int) {
	return file_pb_enum_enum_proto_rawDescGZIP(), []int{1}
}

type SUB_TOPIC int32

const (
	SUB_TOPIC_UNKNOWN_SUB_TOPIC SUB_TOPIC = 0
	SUB_TOPIC_DEFAULT           SUB_TOPIC = 1 // 默认
)

// Enum value maps for SUB_TOPIC.
var (
	SUB_TOPIC_name = map[int32]string{
		0: "UNKNOWN_SUB_TOPIC",
		1: "DEFAULT",
	}
	SUB_TOPIC_value = map[string]int32{
		"UNKNOWN_SUB_TOPIC": 0,
		"DEFAULT":           1,
	}
)

func (x SUB_TOPIC) Enum() *SUB_TOPIC {
	p := new(SUB_TOPIC)
	*p = x
	return p
}

func (x SUB_TOPIC) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SUB_TOPIC) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_enum_enum_proto_enumTypes[2].Descriptor()
}

func (SUB_TOPIC) Type() protoreflect.EnumType {
	return &file_pb_enum_enum_proto_enumTypes[2]
}

func (x SUB_TOPIC) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SUB_TOPIC.Descriptor instead.
func (SUB_TOPIC) EnumDescriptor() ([]byte, []int) {
	return file_pb_enum_enum_proto_rawDescGZIP(), []int{2}
}

type MESSAGE_TYPE int32

const (
	MESSAGE_TYPE_NEW  MESSAGE_TYPE = 0
	MESSAGE_TYPE_RESP MESSAGE_TYPE = 1
)

// Enum value maps for MESSAGE_TYPE.
var (
	MESSAGE_TYPE_name = map[int32]string{
		0: "NEW",
		1: "RESP",
	}
	MESSAGE_TYPE_value = map[string]int32{
		"NEW":  0,
		"RESP": 1,
	}
)

func (x MESSAGE_TYPE) Enum() *MESSAGE_TYPE {
	p := new(MESSAGE_TYPE)
	*p = x
	return p
}

func (x MESSAGE_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MESSAGE_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_enum_enum_proto_enumTypes[3].Descriptor()
}

func (MESSAGE_TYPE) Type() protoreflect.EnumType {
	return &file_pb_enum_enum_proto_enumTypes[3]
}

func (x MESSAGE_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MESSAGE_TYPE.Descriptor instead.
func (MESSAGE_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_pb_enum_enum_proto_rawDescGZIP(), []int{3}
}

type CHAT_TYPE int32

const (
	CHAT_TYPE_UNKNOWN_CHAT_TYPE CHAT_TYPE = 0
	CHAT_TYPE_PRIVATE           CHAT_TYPE = 1 // 私聊
	CHAT_TYPE_GROUP             CHAT_TYPE = 2 // 群聊
)

// Enum value maps for CHAT_TYPE.
var (
	CHAT_TYPE_name = map[int32]string{
		0: "UNKNOWN_CHAT_TYPE",
		1: "PRIVATE",
		2: "GROUP",
	}
	CHAT_TYPE_value = map[string]int32{
		"UNKNOWN_CHAT_TYPE": 0,
		"PRIVATE":           1,
		"GROUP":             2,
	}
)

func (x CHAT_TYPE) Enum() *CHAT_TYPE {
	p := new(CHAT_TYPE)
	*p = x
	return p
}

func (x CHAT_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CHAT_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_enum_enum_proto_enumTypes[4].Descriptor()
}

func (CHAT_TYPE) Type() protoreflect.EnumType {
	return &file_pb_enum_enum_proto_enumTypes[4]
}

func (x CHAT_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CHAT_TYPE.Descriptor instead.
func (CHAT_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_pb_enum_enum_proto_rawDescGZIP(), []int{4}
}

type PLATFORM_TYPE int32

const (
	PLATFORM_TYPE_UNKNOWN_PLATFORM_TYPE PLATFORM_TYPE = 0
	PLATFORM_TYPE_IOS                   PLATFORM_TYPE = 1
	PLATFORM_TYPE_ANDROID               PLATFORM_TYPE = 2
)

// Enum value maps for PLATFORM_TYPE.
var (
	PLATFORM_TYPE_name = map[int32]string{
		0: "UNKNOWN_PLATFORM_TYPE",
		1: "IOS",
		2: "ANDROID",
	}
	PLATFORM_TYPE_value = map[string]int32{
		"UNKNOWN_PLATFORM_TYPE": 0,
		"IOS":                   1,
		"ANDROID":               2,
	}
)

func (x PLATFORM_TYPE) Enum() *PLATFORM_TYPE {
	p := new(PLATFORM_TYPE)
	*p = x
	return p
}

func (x PLATFORM_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PLATFORM_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_enum_enum_proto_enumTypes[5].Descriptor()
}

func (PLATFORM_TYPE) Type() protoreflect.EnumType {
	return &file_pb_enum_enum_proto_enumTypes[5]
}

func (x PLATFORM_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PLATFORM_TYPE.Descriptor instead.
func (PLATFORM_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_pb_enum_enum_proto_rawDescGZIP(), []int{5}
}

type MSG_FROM int32

const (
	MSG_FROM_UNKNOWN_MSG_FROM MSG_FROM = 0
	MSG_FROM_USER             MSG_FROM = 1 // 用户消息
	MSG_FROM_SYSTEM           MSG_FROM = 2 // 系统消息
)

// Enum value maps for MSG_FROM.
var (
	MSG_FROM_name = map[int32]string{
		0: "UNKNOWN_MSG_FROM",
		1: "USER",
		2: "SYSTEM",
	}
	MSG_FROM_value = map[string]int32{
		"UNKNOWN_MSG_FROM": 0,
		"USER":             1,
		"SYSTEM":           2,
	}
)

func (x MSG_FROM) Enum() *MSG_FROM {
	p := new(MSG_FROM)
	*p = x
	return p
}

func (x MSG_FROM) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MSG_FROM) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_enum_enum_proto_enumTypes[6].Descriptor()
}

func (MSG_FROM) Type() protoreflect.EnumType {
	return &file_pb_enum_enum_proto_enumTypes[6]
}

func (x MSG_FROM) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MSG_FROM.Descriptor instead.
func (MSG_FROM) EnumDescriptor() ([]byte, []int) {
	return file_pb_enum_enum_proto_rawDescGZIP(), []int{6}
}

type MSG_TYPE int32

const (
	MSG_TYPE_UNKNOWN_MSG_TYPE MSG_TYPE = 0
	MSG_TYPE_TEXT             MSG_TYPE = 1 // 文本
	MSG_TYPE_POST             MSG_TYPE = 2
	MSG_TYPE_IMAGE            MSG_TYPE = 3
	MSG_TYPE_FILE             MSG_TYPE = 4
	MSG_TYPE_AUDIO            MSG_TYPE = 5
	MSG_TYPE_MEDIA            MSG_TYPE = 6
	MSG_TYPE_STICKER          MSG_TYPE = 7
	MSG_TYPE_INTERACTIVE      MSG_TYPE = 8
	MSG_TYPE_SHARE_CHAT       MSG_TYPE = 9
	MSG_TYPE_SHARE_USER       MSG_TYPE = 10
)

// Enum value maps for MSG_TYPE.
var (
	MSG_TYPE_name = map[int32]string{
		0:  "UNKNOWN_MSG_TYPE",
		1:  "TEXT",
		2:  "POST",
		3:  "IMAGE",
		4:  "FILE",
		5:  "AUDIO",
		6:  "MEDIA",
		7:  "STICKER",
		8:  "INTERACTIVE",
		9:  "SHARE_CHAT",
		10: "SHARE_USER",
	}
	MSG_TYPE_value = map[string]int32{
		"UNKNOWN_MSG_TYPE": 0,
		"TEXT":             1,
		"POST":             2,
		"IMAGE":            3,
		"FILE":             4,
		"AUDIO":            5,
		"MEDIA":            6,
		"STICKER":          7,
		"INTERACTIVE":      8,
		"SHARE_CHAT":       9,
		"SHARE_USER":       10,
	}
)

func (x MSG_TYPE) Enum() *MSG_TYPE {
	p := new(MSG_TYPE)
	*p = x
	return p
}

func (x MSG_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MSG_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_enum_enum_proto_enumTypes[7].Descriptor()
}

func (MSG_TYPE) Type() protoreflect.EnumType {
	return &file_pb_enum_enum_proto_enumTypes[7]
}

func (x MSG_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MSG_TYPE.Descriptor instead.
func (MSG_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_pb_enum_enum_proto_rawDescGZIP(), []int{7}
}

type MUTE_TYPE int32

const (
	MUTE_TYPE_CLOSED MUTE_TYPE = 0 // 关闭免打扰
	MUTE_TYPE_OPENED MUTE_TYPE = 1 // 开启免打扰
)

// Enum value maps for MUTE_TYPE.
var (
	MUTE_TYPE_name = map[int32]string{
		0: "CLOSED",
		1: "OPENED",
	}
	MUTE_TYPE_value = map[string]int32{
		"CLOSED": 0,
		"OPENED": 1,
	}
)

func (x MUTE_TYPE) Enum() *MUTE_TYPE {
	p := new(MUTE_TYPE)
	*p = x
	return p
}

func (x MUTE_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MUTE_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_enum_enum_proto_enumTypes[8].Descriptor()
}

func (MUTE_TYPE) Type() protoreflect.EnumType {
	return &file_pb_enum_enum_proto_enumTypes[8]
}

func (x MUTE_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MUTE_TYPE.Descriptor instead.
func (MUTE_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_pb_enum_enum_proto_rawDescGZIP(), []int{8}
}

type INVITE_ROLE int32

const (
	INVITE_ROLE_UNKNOWN_INVITE_ROLE INVITE_ROLE = 0
	INVITE_ROLE_INITIATOR           INVITE_ROLE = 1 // 发起者
	INVITE_ROLE_APPROVER            INVITE_ROLE = 2 // 审批人
)

// Enum value maps for INVITE_ROLE.
var (
	INVITE_ROLE_name = map[int32]string{
		0: "UNKNOWN_INVITE_ROLE",
		1: "INITIATOR",
		2: "APPROVER",
	}
	INVITE_ROLE_value = map[string]int32{
		"UNKNOWN_INVITE_ROLE": 0,
		"INITIATOR":           1,
		"APPROVER":            2,
	}
)

func (x INVITE_ROLE) Enum() *INVITE_ROLE {
	p := new(INVITE_ROLE)
	*p = x
	return p
}

func (x INVITE_ROLE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (INVITE_ROLE) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_enum_enum_proto_enumTypes[9].Descriptor()
}

func (INVITE_ROLE) Type() protoreflect.EnumType {
	return &file_pb_enum_enum_proto_enumTypes[9]
}

func (x INVITE_ROLE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use INVITE_ROLE.Descriptor instead.
func (INVITE_ROLE) EnumDescriptor() ([]byte, []int) {
	return file_pb_enum_enum_proto_rawDescGZIP(), []int{9}
}

type INVITE_HANDLE_RESULT int32

const (
	INVITE_HANDLE_RESULT_UNKNOWN_INVITE_HANDLE_RESULT INVITE_HANDLE_RESULT = 0
	INVITE_HANDLE_RESULT_ACCEPT                       INVITE_HANDLE_RESULT = 1 // 同意
	INVITE_HANDLE_RESULT_REFUSE                       INVITE_HANDLE_RESULT = 2 // 拒绝
)

// Enum value maps for INVITE_HANDLE_RESULT.
var (
	INVITE_HANDLE_RESULT_name = map[int32]string{
		0: "UNKNOWN_INVITE_HANDLE_RESULT",
		1: "ACCEPT",
		2: "REFUSE",
	}
	INVITE_HANDLE_RESULT_value = map[string]int32{
		"UNKNOWN_INVITE_HANDLE_RESULT": 0,
		"ACCEPT":                       1,
		"REFUSE":                       2,
	}
)

func (x INVITE_HANDLE_RESULT) Enum() *INVITE_HANDLE_RESULT {
	p := new(INVITE_HANDLE_RESULT)
	*p = x
	return p
}

func (x INVITE_HANDLE_RESULT) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (INVITE_HANDLE_RESULT) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_enum_enum_proto_enumTypes[10].Descriptor()
}

func (INVITE_HANDLE_RESULT) Type() protoreflect.EnumType {
	return &file_pb_enum_enum_proto_enumTypes[10]
}

func (x INVITE_HANDLE_RESULT) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use INVITE_HANDLE_RESULT.Descriptor instead.
func (INVITE_HANDLE_RESULT) EnumDescriptor() ([]byte, []int) {
	return file_pb_enum_enum_proto_rawDescGZIP(), []int{10}
}

type AVATAR_OWNER int32

const (
	AVATAR_OWNER_UNKNOWN_AVATAR_OWNER AVATAR_OWNER = 0
	AVATAR_OWNER_USER_AVATAR          AVATAR_OWNER = 1 // 用户头像
	AVATAR_OWNER_CHAT_AVATAR          AVATAR_OWNER = 2 // 群头像
)

// Enum value maps for AVATAR_OWNER.
var (
	AVATAR_OWNER_name = map[int32]string{
		0: "UNKNOWN_AVATAR_OWNER",
		1: "USER_AVATAR",
		2: "CHAT_AVATAR",
	}
	AVATAR_OWNER_value = map[string]int32{
		"UNKNOWN_AVATAR_OWNER": 0,
		"USER_AVATAR":          1,
		"CHAT_AVATAR":          2,
	}
)

func (x AVATAR_OWNER) Enum() *AVATAR_OWNER {
	p := new(AVATAR_OWNER)
	*p = x
	return p
}

func (x AVATAR_OWNER) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AVATAR_OWNER) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_enum_enum_proto_enumTypes[11].Descriptor()
}

func (AVATAR_OWNER) Type() protoreflect.EnumType {
	return &file_pb_enum_enum_proto_enumTypes[11]
}

func (x AVATAR_OWNER) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AVATAR_OWNER.Descriptor instead.
func (AVATAR_OWNER) EnumDescriptor() ([]byte, []int) {
	return file_pb_enum_enum_proto_rawDescGZIP(), []int{11}
}

var File_pb_enum_enum_proto protoreflect.FileDescriptor

var file_pb_enum_enum_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x62, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x70, 0x62, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x2a, 0x3e, 0x0a,
	0x0c, 0x41, 0x43, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x12, 0x18, 0x0a,
	0x14, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x41, 0x43, 0x43, 0x4f, 0x55, 0x4e, 0x54,
	0x5f, 0x54, 0x59, 0x50, 0x45, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x4d, 0x4f, 0x42, 0x49, 0x4c,
	0x45, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x4c, 0x41, 0x52, 0x4b, 0x10, 0x02, 0x2a, 0x24, 0x0a,
	0x05, 0x54, 0x4f, 0x50, 0x49, 0x43, 0x12, 0x11, 0x0a, 0x0d, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57,
	0x4e, 0x5f, 0x54, 0x4f, 0x50, 0x49, 0x43, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x43, 0x48, 0x41,
	0x54, 0x10, 0x01, 0x2a, 0x2f, 0x0a, 0x09, 0x53, 0x55, 0x42, 0x5f, 0x54, 0x4f, 0x50, 0x49, 0x43,
	0x12, 0x15, 0x0a, 0x11, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x53, 0x55, 0x42, 0x5f,
	0x54, 0x4f, 0x50, 0x49, 0x43, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x44, 0x45, 0x46, 0x41, 0x55,
	0x4c, 0x54, 0x10, 0x01, 0x2a, 0x21, 0x0a, 0x0c, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x5f,
	0x54, 0x59, 0x50, 0x45, 0x12, 0x07, 0x0a, 0x03, 0x4e, 0x45, 0x57, 0x10, 0x00, 0x12, 0x08, 0x0a,
	0x04, 0x52, 0x45, 0x53, 0x50, 0x10, 0x01, 0x2a, 0x3a, 0x0a, 0x09, 0x43, 0x48, 0x41, 0x54, 0x5f,
	0x54, 0x59, 0x50, 0x45, 0x12, 0x15, 0x0a, 0x11, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f,
	0x43, 0x48, 0x41, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x50,
	0x52, 0x49, 0x56, 0x41, 0x54, 0x45, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x47, 0x52, 0x4f, 0x55,
	0x50, 0x10, 0x02, 0x2a, 0x40, 0x0a, 0x0d, 0x50, 0x4c, 0x41, 0x54, 0x46, 0x4f, 0x52, 0x4d, 0x5f,
	0x54, 0x59, 0x50, 0x45, 0x12, 0x19, 0x0a, 0x15, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f,
	0x50, 0x4c, 0x41, 0x54, 0x46, 0x4f, 0x52, 0x4d, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x10, 0x00, 0x12,
	0x07, 0x0a, 0x03, 0x49, 0x4f, 0x53, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x41, 0x4e, 0x44, 0x52,
	0x4f, 0x49, 0x44, 0x10, 0x02, 0x2a, 0x36, 0x0a, 0x08, 0x4d, 0x53, 0x47, 0x5f, 0x46, 0x52, 0x4f,
	0x4d, 0x12, 0x14, 0x0a, 0x10, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x4d, 0x53, 0x47,
	0x5f, 0x46, 0x52, 0x4f, 0x4d, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x55, 0x53, 0x45, 0x52, 0x10,
	0x01, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x59, 0x53, 0x54, 0x45, 0x4d, 0x10, 0x02, 0x2a, 0x9d, 0x01,
	0x0a, 0x08, 0x4d, 0x53, 0x47, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x12, 0x14, 0x0a, 0x10, 0x55, 0x4e,
	0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x4d, 0x53, 0x47, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x10, 0x00,
	0x12, 0x08, 0x0a, 0x04, 0x54, 0x45, 0x58, 0x54, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x50, 0x4f,
	0x53, 0x54, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x49, 0x4d, 0x41, 0x47, 0x45, 0x10, 0x03, 0x12,
	0x08, 0x0a, 0x04, 0x46, 0x49, 0x4c, 0x45, 0x10, 0x04, 0x12, 0x09, 0x0a, 0x05, 0x41, 0x55, 0x44,
	0x49, 0x4f, 0x10, 0x05, 0x12, 0x09, 0x0a, 0x05, 0x4d, 0x45, 0x44, 0x49, 0x41, 0x10, 0x06, 0x12,
	0x0b, 0x0a, 0x07, 0x53, 0x54, 0x49, 0x43, 0x4b, 0x45, 0x52, 0x10, 0x07, 0x12, 0x0f, 0x0a, 0x0b,
	0x49, 0x4e, 0x54, 0x45, 0x52, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x10, 0x08, 0x12, 0x0e, 0x0a,
	0x0a, 0x53, 0x48, 0x41, 0x52, 0x45, 0x5f, 0x43, 0x48, 0x41, 0x54, 0x10, 0x09, 0x12, 0x0e, 0x0a,
	0x0a, 0x53, 0x48, 0x41, 0x52, 0x45, 0x5f, 0x55, 0x53, 0x45, 0x52, 0x10, 0x0a, 0x2a, 0x23, 0x0a,
	0x09, 0x4d, 0x55, 0x54, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x4c,
	0x4f, 0x53, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x4f, 0x50, 0x45, 0x4e, 0x45, 0x44,
	0x10, 0x01, 0x2a, 0x43, 0x0a, 0x0b, 0x49, 0x4e, 0x56, 0x49, 0x54, 0x45, 0x5f, 0x52, 0x4f, 0x4c,
	0x45, 0x12, 0x17, 0x0a, 0x13, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x49, 0x4e, 0x56,
	0x49, 0x54, 0x45, 0x5f, 0x52, 0x4f, 0x4c, 0x45, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x49, 0x4e,
	0x49, 0x54, 0x49, 0x41, 0x54, 0x4f, 0x52, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x41, 0x50, 0x50,
	0x52, 0x4f, 0x56, 0x45, 0x52, 0x10, 0x02, 0x2a, 0x50, 0x0a, 0x14, 0x49, 0x4e, 0x56, 0x49, 0x54,
	0x45, 0x5f, 0x48, 0x41, 0x4e, 0x44, 0x4c, 0x45, 0x5f, 0x52, 0x45, 0x53, 0x55, 0x4c, 0x54, 0x12,
	0x20, 0x0a, 0x1c, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x49, 0x4e, 0x56, 0x49, 0x54,
	0x45, 0x5f, 0x48, 0x41, 0x4e, 0x44, 0x4c, 0x45, 0x5f, 0x52, 0x45, 0x53, 0x55, 0x4c, 0x54, 0x10,
	0x00, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x43, 0x43, 0x45, 0x50, 0x54, 0x10, 0x01, 0x12, 0x0a, 0x0a,
	0x06, 0x52, 0x45, 0x46, 0x55, 0x53, 0x45, 0x10, 0x02, 0x2a, 0x4a, 0x0a, 0x0c, 0x41, 0x56, 0x41,
	0x54, 0x41, 0x52, 0x5f, 0x4f, 0x57, 0x4e, 0x45, 0x52, 0x12, 0x18, 0x0a, 0x14, 0x55, 0x4e, 0x4b,
	0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x41, 0x56, 0x41, 0x54, 0x41, 0x52, 0x5f, 0x4f, 0x57, 0x4e, 0x45,
	0x52, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x41, 0x56, 0x41, 0x54,
	0x41, 0x52, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x48, 0x41, 0x54, 0x5f, 0x41, 0x56, 0x41,
	0x54, 0x41, 0x52, 0x10, 0x02, 0x42, 0x20, 0x5a, 0x1e, 0x6c, 0x61, 0x72, 0x6b, 0x2f, 0x70, 0x6b,
	0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x62, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x3b,
	0x70, 0x62, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_enum_enum_proto_rawDescOnce sync.Once
	file_pb_enum_enum_proto_rawDescData = file_pb_enum_enum_proto_rawDesc
)

func file_pb_enum_enum_proto_rawDescGZIP() []byte {
	file_pb_enum_enum_proto_rawDescOnce.Do(func() {
		file_pb_enum_enum_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_enum_enum_proto_rawDescData)
	})
	return file_pb_enum_enum_proto_rawDescData
}

var file_pb_enum_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 12)
var file_pb_enum_enum_proto_goTypes = []interface{}{
	(ACCOUNT_TYPE)(0),         // 0: pb_enum.ACCOUNT_TYPE
	(TOPIC)(0),                // 1: pb_enum.TOPIC
	(SUB_TOPIC)(0),            // 2: pb_enum.SUB_TOPIC
	(MESSAGE_TYPE)(0),         // 3: pb_enum.MESSAGE_TYPE
	(CHAT_TYPE)(0),            // 4: pb_enum.CHAT_TYPE
	(PLATFORM_TYPE)(0),        // 5: pb_enum.PLATFORM_TYPE
	(MSG_FROM)(0),             // 6: pb_enum.MSG_FROM
	(MSG_TYPE)(0),             // 7: pb_enum.MSG_TYPE
	(MUTE_TYPE)(0),            // 8: pb_enum.MUTE_TYPE
	(INVITE_ROLE)(0),          // 9: pb_enum.INVITE_ROLE
	(INVITE_HANDLE_RESULT)(0), // 10: pb_enum.INVITE_HANDLE_RESULT
	(AVATAR_OWNER)(0),         // 11: pb_enum.AVATAR_OWNER
}
var file_pb_enum_enum_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_enum_enum_proto_init() }
func file_pb_enum_enum_proto_init() {
	if File_pb_enum_enum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_enum_enum_proto_rawDesc,
			NumEnums:      12,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_enum_enum_proto_goTypes,
		DependencyIndexes: file_pb_enum_enum_proto_depIdxs,
		EnumInfos:         file_pb_enum_enum_proto_enumTypes,
	}.Build()
	File_pb_enum_enum_proto = out.File
	file_pb_enum_enum_proto_rawDesc = nil
	file_pb_enum_enum_proto_goTypes = nil
	file_pb_enum_enum_proto_depIdxs = nil
}
